microsoft/pxt-arcade

sim/controlPad.ts, sim/public/sim.css, sim/public/simulator.html, sim/simulator.ts, sim/svg.ts
Add support for a control pad UI and makes the sim full screen.
The `svg.ts` business is a little SVG rendering library I wrote while working on the sprite editor and getting frustrated with what we have in pxsim. I'll move it to PXT eventually, but I'm putting it here for now so that I can iterate on it faster.
=> Fullscreen sim with visible controls (v1)

docs/docs.md, docs/examples/asteroids.md, docs/examples/car-race.md, docs/examples/duck.md, docs/examples/jumper.md, docs/examples/mega-bounce.md, docs/examples/runner.md, docs/examples/snake.md, libs/blocksprj/main.blocks, libs/core/control.ts, libs/core/sims.d.ts, libs/game/game.ts, libs/game/sprites.ts, package.json, sim/api.ts
To stay compatible with the other targets, we only support "frame" in pxt-32 (better name maybe). Forever is not available so that it does not bring confusion and code produced here would still be compatible in common packages.
=> Remove forever for frame

libs/core/buffer.d.ts, libs/core/control.ts, libs/core/sims.d.ts, libs/keys/enums.ts, libs/keys/keys.ts, libs/keys/pxt.json, libs/keys/targetoverrides.ts, sim/api.ts, sim/simulator.ts
C++ uses numbers so it's easier to use this datatype to declare events.
=> Use number instead of strings for events

sim/controlPad.ts, sim/public/sim.css, sim/simulator.ts
Fix a bunch of sim resizing issues. 
Blur controls when not in focus.
Focus on mouse over of controls.
=> Blur controls when not in focus (+ resizing fixes)

editor/bitmap.ts, editor/bitmapImage.ts, editor/buttons.ts, editor/grid.ts, editor/spriteEditor.ts, editor/spriteFieldEditor.ts, editor/toolbar.ts, editor/tools.ts, sim/svg.ts
Fixes https://github.com/Microsoft/pxt-32/issues/43
New features:
1. Tool size option
2. Canvas resizing
3. Fill tool (icon is a magic wand, will change later)
4. Background for sprite on the block
4. Lots of bug fixes and perf improvements
=> More sprite editor improvements

editor/buttons.ts, editor/spriteEditor.ts, editor/spriteFieldEditor.ts, editor/toolbar.ts, sim/svg.ts
New options:
```typescript
//% img.fieldOptions.initWidth=12
//% img.fieldOptions.initHeight="13"
//% img.fieldOptions.initColor=7
//% img.fieldOptions.sizes="4,4;12,13;45,45"
```
* `initWidth/initHeight` set the initial sprite size
* `initColor` sets the color that is selected in the palette by default 
* `sizes` is a semicolon separated list of size pairs for the resize button. Setting it to empty (e.g. "") will cause the resize button to be hidden
@pelikhan this also fixes the issue you had with changing the cursor size while the fill tool is selected
=> Adding options to the sprite editor

theme/blockly.less, theme/style.less
Moving Blockly toolbox css to semantic.css as per https://github.com/Microsoft/pxt/pull/4132
=> Move blockly toolbox css to semantic.css

docfiles/abuse.html, docfiles/script.html
Fixes https://github.com/Microsoft/pxt-arcade/issues/163. 
Note: this change goes live when PR is checked in. 
@abchatra @pelikhan please discuss this design, and let me know if there are any changes you'd like me to make.
Mobile: 
(Small banner, optimized to show editor)
Desktop: 
(Bigger banner)
Both make use of the entire screen as much as possible
=> Fix share page layout issues

docs/reference/game.md, libs/device/ns.ts
Add a _game.md_ card page override to include target local **reset** and **runtime** functions.
=> Add  'game' api override card page

pxtarget.json
I left the other openocd for reference; in future we might want `--stlink`/`--cmsis` options to `pxt gdb` but for now it seems stlink is more reliable, cheaper, and already used in the stm32 target
=> Use stlink for hw-debugging also on SAMD51

sim/public/sim.css, sim/public/simulator.html, sim/simulator.ts
Debug stats are now shown on screen instead than in the DOM. Allow to see them on hardware too.
=> debug stats on screen

docs/examples/eater-princess.md
Changes the following things:
* Removes tile map since it was redundant with the stay-on-screen flag
* Changes SpriteKinds to use the default SpriteKinds and consistently all uppercase
* Removes initialization for variable ```sprite``` since it was never used and just gets set to ```null```. (Possibly a decompiler issue with sprite overlap events that don't use both parameter)
* Switches random logic to use percentChance
@abchatra
=> A few minor tweaks to the Eater Princess example

docs/lessons.md
Removes the cardType of lessons so that they correctly link to the docs as suggested in Microsoft/pxt#5090
Fixes Microsoft/pxt-arcade#374
=> Removed lesson card type to allow linking to docs

pxtarget.json
Fixes https://github.com/Microsoft/pxt-arcade/issues/443
We haven't decided on what the saving story should look like, so this PR is turning off save as PNG and moving the save button into the gearwheel.
Things to discuss about saving:
* Should we save as UF2? If so, how do you choose hardware and what if you have no hardware? 
* If we have WebUSB on, how do you save your project locally in a format that can be flashed onto the hardware?
=> Save as .mkcd and move button to the menu

sim/controlPad.ts, sim/simulator.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/444
Fixes https://github.com/Microsoft/pxt-arcade/issues/295
Fixes https://github.com/Microsoft/pxt-arcade/issues/288
Fixes https://github.com/Microsoft/pxt-arcade/issues/412
This PR does the following:
1. Make the menu/reset buttons scale their size and padding
2. Hide the controls in tablet view (so you just see the screen)
3. Remove the screen bevels in Internet Explorer
=> Fix a few simulator layout edge cases

sim/simulator.ts
This fixes #442
That code looks seriously inefficient though. Is it only so that Edge renders the thing without smoothing?
=> Fix for artifacts when screen is cleared with invalid color

docs/examples/eater-princess.md, docs/examples/space-destroyer.md
`let sprite: Sprite = null` and `let otherSprite: Sprite = null` declarations are not necessary in example code if those variables are only used inside a sprite event. With the reporter changes, these declarations actually show up in the blocks as a gray block, so let's get rid of them. All our other examples don't have these declarations.
Tested on v0.2.35 (live) and latest master
Changes without whitespace: https://github.com/Microsoft/pxt-arcade/pull/487/files?w=1
=> Remove unneeded var declarations in examples

sim/simulator.ts
We start an interval to unstuck the simulator but it does not seem to be used. Disabling for now.
=> disable unused interval

libs/screen---st7735/targetoverrides.ts, package.json, sim/public/sim.css, sim/public/simulator.html, sim/simulator.ts
Use the bottom 8 pixels for displaying stats when requested from menu. Use the old overlay text element in simulator.
Requires https://github.com/Microsoft/pxt-common-packages/pull/633
Fixes https://github.com/Microsoft/pxt-arcade/issues/542
=> Limit hardware screen to 120px high

sim/controlPad.ts
Fix for https://github.com/Microsoft/pxt-arcade/issues/438
It seems that IE gets it's "focus" state messed up.
=> always focus on keystroke

package.json, sim/api.ts, sim/controlPad.ts, sim/public/sim.css, sim/simulator.ts
The "reset" button used to handle a click on the SVG element. Since we swallow all mouse/touch events, it wasn't being triggered anymore. Making it a proper control pad button with multi-touch and all.
=> Repairing Reset button

package-lock.json
We made the sim optional in package.json but never updated the package-lock.json. As a result, npm was ignoring the optional setting.
Should fix https://github.com/Microsoft/pxt-arcade/issues/698
Hurray for package lock!
=> Update package lock becausd sim is now optional

pxtarget.json
Requires https://github.com/Microsoft/pxt-blockly/pull/199 and a bump to latest pxt-core for this to take effect
=> Add default arg name for sprite types

package.json
I was getting authentication errors on installing through https (sound like I forgot to set up git credentials manager), and https://github.com/npm/npm/issues/11567 had a suggestion to use the 'github shortcut syntax', which will try https, ssh, and git for authentication before failing
=> use github shortcut syntax for sim install

libs/screen---linux/targetoverrides.ts, libs/screen---st7735/targetoverrides.ts, libs/screen/targetoverrides.ts, package.json, pxtarget.json
See https://github.com/mmoskal/uf2-stm32f/releases for bootloader with deep sleep support
requires https://github.com/Microsoft/pxt-common-packages/pull/700
=> Enable screen brightness API and deep sleep mode

pxtarget.json
Maybe this should be default for all targets, but for sure for new ones - custom.ts is replaced by packages.
=> Make the [+] button add an arbitrary new file, not custom.ts

docs/concepts/setting-the-scene.md, docs/courses/csintro2/tilemap/intro.md, docs/courses/csintro3/structure/tilemaps.md, docs/examples/cube-land.md, docs/examples/planet-putt-putt.md, docs/examples/treasure-hunt.md, docs/projects.md, docs/tutorials/simple-maze.md
set tile was changed to make the final param non-optional in blocks, so this adds them in to the examples set tile is used so it doesn't decompile with a hole
ran checkdocs locally and it passed, this travis build should fail due to the fork issue
=> add false as param so blocks `set tile` decompile w/ field editor

libs/sevenseg/sevenseg.ts
Fix spelling errors found by translators.
RE: Crowdin issues -
* https://crowdin.com/translate/kindscript/5814/en-es#401028
* https://crowdin.com/translate/kindscript/5814/en-es#401026
* https://crowdin.com/translate/kindscript/5814/en-es#401032
=> Bad spelling in 'sevenseg' jsdoc text

theme/style.less
Center's the play icon on the screen, as mentioned in https://github.com/Microsoft/pxt/pull/5404
=> Center the play icon on the screen of the sim in desktop

docs/concepts/star-field.md
I put the change in step 2 where the block is first used. How's that?
Fixes #845 
@jwunderl
=> Mention non-default vx and vy in 'Starfield'

docs/tutorials/simple-maze.md
Split out step 10 to step 11 for more detail on using gameOver().
Also, why is the effect option rendering on gameOver() when only the win parameter is given (docs only)?
Fixes #844
=> Fix step 10 of 'Simple Maze' tutorial

pxtarget.json
Share to forum info. Requires https://github.com/Microsoft/pxt/pull/5453 but harmless without.
=> discourse social sharing settings

docs/examples/jumpy-platformer.md
Very minor change, but richard pointed out that the player doesn't bounce on the enemy ( / it just continues to fall down), and adding a bounce is very satisfying.
=> add slight bounce on top of enemies

theme/site/globals/site.variables
Don't use monospace fonts for text in docs.
=> use docs fonts for docs

docs/lessons/barrel-dodger.md
closes https://github.com/Microsoft/pxt-arcade/issues/924
Add full game solution at the bottom of the lesson, and cut a step that says to add a block then never adds it (the next step places the barrel on the tile map)
=> Add solution to barrel dodger, remove unused step

docs/examples/particle-effects-demo.md
I had the radials being created with pauses so they show up spinning nicely, but that causes the rest of the effects to be delayed.
This just makes it so if you have multiple effects running (you pressed ``a`` a couple times) the others won't get delayed if the first one is a radial effect.
=> Run radials in parallel so effects show up at same time

targetconfig.json
I made this a while back and it can be fairly useful for different types of games (fighting games, dance dance revolution type games, etc)
repo: https://github.com/jwunderl/pxt-button-combos
this one is like a typing game but for button sequences (note that + between two buttons means 'press these at the same time'): https://arcade.makecode.com/34820-28382-49062-64224
More thorough explanation on forum: https://forum.makecode.com/t/combo-attack-and-button-combination-extension/169
One thing I was thinking about was how to make the combos easier to visualize in blocks / not just a string of text. I could add an enum of the different buttons and a block to get the button for that, but that's a bit clunky as the blocks would still have to be ``join``ed. Seems like it would need it's own …
=> Add button combos extension to approved repos

editor/extension.ts, pxtarget.json
fixes https://github.com/microsoft/pxt-arcade/issues/1009
Patch old enum SpriteKind to SpriteKindLegacy
=> fix user enums upgrade (SpriteKind -> SpriteKind.Legacy)

libs/hw---vm/sdlmain.cpp
requires https://github.com/microsoft/pxt-common-packages/pull/857
This adds hooks into JavaScriptCore to compile on-device on iOS
=> Use JSC compilation and pxt_vm_start_buffer

pxtarget.json
Fix for https://github.com/microsoft/pxt-arcade/issues/1063
=> hide power blocks

libs/corgio/corgio.ts, libs/darts/darts.ts
fixes https://github.com/microsoft/pxt-arcade/issues/1102
Use the new namespace kinds instead of the old enum kinds, which works https://makecode.com/_EUXXaDYd3W2E
=> enum->namespace for sprite kinds

pxtarget.json
This merges @jamesadevine merge-i2c_hack branch on the codal side, which should hopefully fix freezes/almost-freezes when using accelerometer on SAMD51
Also, it places 512k limit on games for SAMD, so we get an error when they get too big.
CC @gitri-ms
=> Bump codal-samd to 0.2.2 to fix accel freeze

docs/concepts/bouncing-burger.md, docs/concepts/picnic-food.md, docs/concepts/princess-pizza.md, docs/concepts/setting-the-scene.md, docs/concepts/sunday-drive.md, docs/concepts/throw-a-bone.md, docs/concepts/walking-hero.md, docs/concepts/which-button.md, docs/courses/csintro3/about/start.md, docs/courses/csintro3/arrays/sprites-problems.md
Missing forward slash in direct tutorial links...
Closes #1115
=> Repair direct tutorial linkouts

targetconfig.json
Adds https://github.com/jwunderl/pxt-color to approved repos
Starting as a draft as I'd love some feedback on the package itself whenever anyone has time, not sure on the wording of the blocks / which api's may be needed or unneeded /  etc.
~I definitely still need to resize all the images for the jres and compress them or actually do something proper for them, as I tried sharing and sometimes it didn't seem to work due to file size from all the quick screenshots for the block icons~ resized all images
https://makecode.com/_C4eVqmcqXDRq
eventually I'd like to add blocks for defining a color palette as well, but that would need a nice field editor to work at all - something like http://hslpicker.com/#1416a9 or the standard-ish rainbow square + luminosity slider, with the 15 / 16 color …
=> add pxt-color to approved / preferred repos

docs/hardware.md
We've changed the website and need to change the link.
=> Fixed Link to BrainPad website

docs/blocks-games/catch.md
clean up the catch game, as it had a few unused things / old sprite kinds / sprites that were bigger than necessary. Also makes it use the ``bounce on walls`` flag to simplify the code (and fix the issue here)
https://makecode.com/_JxrC7L8vmK6x
This game was relying on the speed staying the same and the tile map just stopping the sprite to work, which is pretty wonky behavior that doesn't work properly with acceleration (e.g. when I get out of bed I don't hit the ground at terminal velocity from gravity pulling me down all night, and a platformer character shouldn't fall into a hole at 500 pixels per second just because the player didn't jump)
re https://github.com/microsoft/pxt-arcade/issues/1143, but somewhat tangential; this fixes the game itself but I can make it so the current …
=> clean up catch game example

package.json
Our CLI assumes that the npm package name is ``pxt-${pxtarget id}``. The cloud does not rely on the package.json name entry.
=> renampe npm package from pxt-32 to pxt-arcade

pxtarget.json
Currently it's just junk, resulting in useless descriptions on google searches:
=> add description for arcade homepage

docs/lessons/cherry-pickr.md
Fixes #1147.
For some reason, my local repo won't let me open documentation files. When I click on a link from the main page to open a doc, the server complains about a missing `pxt.json` file in `jacdac-drivers`. So, I've only read through the MarkDown. I'm not able to check if it renders properly. :-)
```
opening http://localhost:3232/#local_token=...&wsport=3233
INTERNAL ERROR: Error: ENOENT: no such file or directory, open 'F:\A\TFS\akulcsar\PXT\pxt-arcade\libs\jacdac-drivers\pxt.json'
at Object.openSync (fs.js:439:3)
at Object.readFileSync (fs.js:344:35)
at readJson (F:\A\TFS\akulcsar\PXT\pxt-arcade\node_modules\pxt-core\built\nodeutil.js:263:26)
at readPkgConfig (F:\A\TFS\akulcsar\PXT\pxt-arcade\node_modules\pxt-core\built\nodeutil.js:269:14)
at Object.resolveMd …
```
=> Update Cherry Pickr lesson with current blocks.

libs/hw---samd51/config.ts
This PR removes config overrides for the JACDAC pin on pybadge and pygamer.
The reason for the original override is that the current hardware layout for PA23 (D13), used for JACDAC communications, has an LED that causes a voltage drop bringing the idle state of the line to ~1.6v:
(top trace shows digital equivalent of bottom analog trace)
As the microcontroller does not register 1.6v as a logical one, it is not a valid idle condition in JACDAC. Instead, we defined PA23 to be used as the COMM_LED for JACDAC, and PA04 (A4) to be used for JACDAC comms as PA04 does not have any additional hardware components that causes a drop in voltage.
=> Remove bootloader config overrides for JACDAC on pybadge/gamer

libs/animation/pxt.json, libs/controller/pxt.json, libs/corgio/pxt.json, libs/darts/pxt.json, libs/edge-connector/pxt.json, libs/feather/pxt.json, libs/feather/targetoverrides.d.ts, libs/palette/pxt.json, libs/rotary-encoder/pxt.json, libs/storyboard/pxt.json
Expose pins A8, A9 (JST connectors) on py***
Requires https://github.com/microsoft/pxt-common-packages/pull/909
Requires https://github.com/microsoft/pxt-common-packages/pull/912
Requires https://github.com/microsoft/pxt/pull/5783 (will still work without it)
=> specialize feather support on arcade

docs/courses/csintro1/about/authors.md, docs/courses/csintro1/project/example.md, docs/courses/csintro1/sprites/unplugged.md, docs/courses/csintro2/about/authors.md
Some images got replaced recently from .png's to .jpg's which broke any image that linked to it.
This switches the links to point to the proper images.
=> Fixed image links

docs/tutorials/chase-the-pizza.md
Fixes #1275.
Because there was no context for this block, it was placed into the default `on start` block. Added context so that the containing block is rendered correctly.
=> Chase the pizza edit

docs/nfl.html
[arcade.makecode.com/nfl](arcade.makecode.com/nfl) is looking ugly because semantic isn't being loaded properly as the doccdn isn't getting switched out; this just switches to load from scripthead in the docfiles which should get the doccdn switched out properly. Oops.
(also ``display: block !important;`` because one of the other rules from scripthead was messing up the layout by making the root flex)
=> fix nfl page by actually loading semantic

docs/nfl.html
re: simulator being small and not working for really small phones (especially in edge with resizing issues)
Make the simulator take up a larger portion of the page and resize properly
~~Worth noting that the 105% height on ``#simulator iframe`` is different from the default generated for simulator embeds, but I think we might need to fix something there - without it I pretty consistently get behavior where the bottom gets clipped when not focused.~~ issue is with footer not getting displayed properly.
Repros with just the default share embed https://jsfiddle.net/nqvtuyxs/1/ if it doesn't look messed up right away, you might need to click on the simulator and then click away
=> fix nfl page simulator resizing

package.json
New position picker shows a blank screen but github won't allow to upload pngs.
=> bump pxt to 5.26.8

pxtarget.json
fix https://github.com/microsoft/pxt-arcade/issues/1355 (see also https://github.com/microsoft/pxt-electron/pull/164)
infinite spinning was from an attempt to deploy to a volume that wasn't allowed on mac (and probably any wrote the file to any drives on windows, unless it silently failed?), which ended up failing to propagate the completion of the promise.
this just uses the default drive name for the rpi0, meaning it will pop up the save dialogue for any other board for now; I would think it would be ideal if boards could standardize around that one name (easier for tutorials / examples / dialogues to be consistent rather than just `drag this file over to whatever random drive shows up that wasn't there before`) but that seems unlikely
Also probably worth eventually moving hardware …
=> use rpi0 as default deploy drive

docs/nfl.html
quick patch for nfl page to work with docs2.0; one of the classes added to the footer changed it's color to arcade red, otherwise everything else looked about the same already.
=> make footer match background color

pxtarget.json
together with https://github.com/microsoft/pxt-common-packages/pull/1005 this fixes backlight on SAMD
only new change is https://github.com/lancaster-university/codal-samd/commit/8e4b828d06c2c36dfa953467e2e9cfd135994fb5
=> Codal 0.2.6 on SAMD - allows freeing PWM

docs/tutorials/lemon-leak.md
Fix the instructions for `math.randomRange()` to match block default parms.
Fixes #1524
=> Match step description to block in 'Lemon Leak'

docs/tutorials/simple-extensions.md
The block for ``myCorg.verticalMovement()`` was missing in the hint for ``Step 2``.
Fixes #1535
=> Add missing block to 'Simple Extension' hint

docs/blocks-games/duck.md
Use an invisible "gap" sprite as a threshold to score the duck's successful passage.
Fixes #1525
=> Use threshold sprite for 'Falling Duck" score

docs/tutorials/name-tag.md
fix https://github.com/microsoft/pxt-arcade/issues/1595
the behavior of unplugged portions only showing up on the modal and not on the step itself feels a bit off here, as the last step is unplugged too, leaving you with an empty hint; can add a last step here saying "congrats" or something of the sort?
=> fix snippet in name tag tutorial

docs/blocks-games/duck.md
latest falling duck has a gray block at the moment, because there is no block for image.width (also having 2 here feels like it ends up overlapping more consistently with when I would expect to score, but that's arguable)
=> remove gray block from falling duck (no image.width block)

docs/courses/csintro3/about/start.md, docs/tutorials.md
As per our discussions in Teams
=> move maze tutorial to back of list

docs/tutorials/lander.md
=> Fix Step 7 in the Lander tutorial

libs/template/.gitattributes, libs/template/assets/index.html, libs/template/assets/js/loader.js, libs/template/index.html, libs/template/pxt.json, package.json
Update template to bust cache of .js files in github pages + display version.
=> GitHub pages cache busting

pxtarget.json
Enable collapsing of blocs event as an experiment. Requires https://github.com/microsoft/pxt/pull/6487
=> enable blocks collapsing experiment

scripts/copyArcadeSim.js
Adding a script to copy over pxt-arcade-sim into a local copy of pxt-arcade (not a symlink). It both copies the relevant files and changes `tsconfig.json` so that it builds correctly.
I did not add a note to the README because the sim repo is private.
=> Adding script for copying over pxt-arcade-sim

README.md
Insert a document viewing note in the repo's `README.md`. This is a follow up to #1758.
=> Doc viewing in GitHub note

pxtarget.json
@Jaqster reported that the context menu option for launching the sidedocs in monaco wasn't working. Turns out we just never enabled it in arcade.
=> Enabling help option in monaco

docs/courses/csintro.md, docs/courses/csintro1.md, docs/courses/csintro1/intro.md, docs/courses/csintro1/loops.md, docs/courses/csintro1/motion.md, docs/courses/csintro1/sprites.md, docs/courses/csintro2.md, docs/courses/csintro2/arrays.md, docs/courses/csintro2/functions.md, docs/courses/csintro2/logic.md, docs/courses/csintro2/tilemap.md
Add the Flipgrid flipcode and topic links for CSIntro. Covers beginner courses 1 & 2.
=> Insert Flipgrid links in CSIntro pages

docs/courses/csintro2/arrays/project.md, docs/courses/csintro2/arrays/string.md, docs/courses/csintro2/arrays/tilemap.md, docs/courses/csintro2/functions/project.md, docs/courses/csintro2/logic/project.md, docs/courses/csintro2/review/side-scroller.md, docs/courses/csintro2/tilemap/extensions.md, docs/courses/csintro2/tilemap/interactions.md, docs/courses/csintro2/tilemap/intro.md, docs/courses/csintro2/tilemap/project.md, docs/courses/csintro3/arrays/project.md, docs/courses/csintro3/arrays/tiles-problems.md, docs/courses/csintro3/arrays/tiles.md, docs/courses/csintro3/events/info-problems.md, docs/courses/csintro3/events/project.md, docs/courses/csintro3/functions/project.md, docs/courses/csintro3/structure/project.md, docs/courses/csintro3/structure/tilemaps-problems.md, docs/courses/csintro3/structure/tilemaps.md
Apparently the snippets in the course never got the package snippet, and I had never noticed because they just showed gray blocks (as the color-coded-tilemap extension just adds the block definitions)
Adds a little header to those pages explaining why they use different blocks, and include the package so the snippets don't get gray blocks:
re: https://forum.makecode.com/t/noob-question-unable-to-create-stage-map-for-the-game/1571/3?u=jwunderl
also fixed the project subheadings on hints, as they looked wonky; with this they'll show up on the same line as the hint icon, rather than underneath:
worth noting we can't really upgrade course 3 fully right now, as that one's js based and there is currently no tilemap editor in monaco; color-coded-tilemap is the only option staying in there atm
=> add note on color-coded-tilemap, and import pkg

targetconfig.json
I created [this extension](https://github.com/microsoft/pxt-settings-blocks) to wrap the settings namespace for blocks. Adding this to the preferred repo list so that it shows up in the extensions dialog. 
The settings blocks can be used to save/restore data for a game in between runs. For example, you can use it to save your progress in a long game, track how many times a player has died, etc. The blocks are below
=> Adding settings package to preferred list

docs/tutorials/simple-extensions.md
Set `game.over(true)` so **WIN** shows in the snippet block. This matches the description.
Fixes #1995
=> Set WIN for 'Simple Extensions'

docs/tutorials/barrel-dodger.md
Change the mention of "any button" to "A button" in the Barrel Dodger tutorial.
Closes #2031
=> Say Button 'A' in 'Barrel Dodger'

docs/tutorials.md, docs/tutorials/spy/chase-the-pizza.md, docs/tutorials/spy/happy-flower.md, docs/tutorials/spy/lemon-leak.md
Copy and convert block-style tutorials to 'spy' tutorials - #2013.
Tutorials that seem "practical" for 'spy':
Tutorials already generalized:
The remaining tutorials have very large sprite/background images or complicated tilemap structures.
**Comments**:
* Python is not currently enabled for this target. Snippets will need set to ```` ```typescript ```` to do just JS in tutorials.
* Also, ``otherActions`` seems to not work for explicit 'spy' tutorials - gets a `409` response on those. They will load if I use a direct `#tutorial:` url.
Closes #2013
=> Spyify tutorials

package.json
pxt-arcade-sim already updated to v0.7.19, but please verify it looks right.
=> bump pxt-arcade-sim version

docs/concepts/breadcrumb-trail.md
Update step description to match new block text.
Fixes #2089
=> Fix tile array text in 'Breadcrumb Trail'

docs/courses/csintro3/about/case-study.md, docs/courses/csintro3/arrays/case-study.md, docs/javascript-games/planet-putt-putt.md
Few typos where fields (getters) were called with parentheses, this was allowed accidentally till https://github.com/microsoft/pxt/pull/7317. Fixes build
local build since travis will take a while:
=> fix doc breaks from object assignability fix

docs/recipes/shark-splash/04-background.md
Incorrect variable name for `mySprite`, snippet didn't completely decompile. So...the block was missing from the toolbox selections.
Fixes #2134
Fixes #2148
=> Fix var name in Shark Attack background tutorial

editor/extension.ts
fix https://github.com/microsoft/pxt-arcade/issues/2232
https://github.com/microsoft/pxt/pull/7347 fixed the block upgrade path up a bit as we were hitting exceptions depending on the blocks (it looks like it was at least whenever a project had the `Sprite.image` block. This in theory is good, as it means upgrade rules are being applied properly, but in this case the upgrade rule produced a set of blocks that was valid XML / compiled to a syntactically valid program that did not match meaning original code, and the program had 'worked' when we bailed to typescript and did the regex replaces. (I described the issue in the comment in the PR, but the issue is that the getters for SpriteKindLegacy were being set improperly getting replaced with the default value `SpriteKindLegacy.Player`) …
=> fix upgrade rule for spritekind enums

docs/game-jam.md, docs/projects.md, targetconfig.json
Should be merged in after Arcade release (Garden Crop Duster created in beta, and also requires the upgrade rules for the pxt-tilemaps extension)
=> Add gamejam winners row to home page

docs/tutorials/barrel-dodger.md
Mention setting `vy` for the projectile to `0`.
Closes #2244
=> Mention setting vy to zero in Barrel Dodger

package.json
most recent bump is [8.1.2](https://github.com/microsoft/pxt-common-packages/commit/791e8cce1f7d6b4367b2152fafc52785039d89eb)
=> fix common packages dep 8.1.12 -> 8.1.2

docs/tutorials/spy/happy-flower.md
Step 10 of "Happy Flower" assumed that the user would know to set the image instance to `projectile.image`. However, if they are grabbing code bits from the toolbox things can get strange with the default instance attached to `flipX()`. So, an additional sentence is added to help in that case.
Closes #2258
=> Add more info to 'Happy Flower' step 10

docs/tutorials/name-tag.md
Remove `@unplugged` from the last step in tutorial to avoid the popup annoyance.
Fixes #2060
=> Remove unplugged in 'Name Tag' tutorial

docs/recipes/shark-splash/02-C-enemies.md
Hint block was missing in Step 2 of '`02-C-enemies`.
Closes #2356
=> Include missing hint in Shark Attack '02-C'

targetconfig.json
release version 1.2.7 to pick up https://github.com/microsoft/pxt-arcade/pull/2409
Tested that it downloads / installs on both my windows and mac devices; the only difference is in the docs, but we can test a bit more if you want as well.
=> Offline app release v1.2.7

docs/lessons/dance-party.md
Convert the tilemap to jres so that the `tiles.setTileMap()` works in the document render.
RE #2414, #2418
=> Convert tilemap in "Dance Party" to jres

docs/lessons/cherry-pickr.md
Convert the tilemap to jres so that the `tiles.setTileMap()` works in the document render. Also, restyle the hint sections.
Fixes #2414
=> Convert 'Cherry Pickr' tilemap to jres

libs/sevenseg/sevenseg.ts
Some fixes to the **sevenseg** extension.
=> Few fixes to 'sevenseg' extension

docs/recipes/side-scroller/03-control-car.md
Using both an image and a block code hint can be visually confusing to the user. The steps with this situation are modified to use one or the other based on what action is being described.
* Step 3 (4) - use code hint to show bottom wall selection
* Step 6 (7) - use the image to show pulling out two tile overlap blocks 
* Step 7 (8) - use code hint to show selecting tiles for the overlap blocks
Closes #2461
=> Side Scroller 3 - use either code hint or image in steps

docs/courses/csintro2/arrays/intro.md, docs/courses/csintro2/arrays/sprites.md, docs/courses/csintro2/arrays/string.md, docs/courses/csintro2/arrays/tilemap.md, docs/courses/csintro2/functions/extensions.md, docs/courses/csintro2/functions/intro.md, docs/courses/csintro2/functions/redundancy.md, docs/courses/csintro2/logic/booleans.md, docs/courses/csintro2/logic/intro.md, docs/courses/csintro2/logic/multiplayer.md, docs/courses/csintro2/logic/user-input.md, docs/courses/csintro2/logic/while.md, docs/courses/csintro2/tilemap/extensions.md, docs/courses/csintro2/tilemap/interactions.md, docs/courses/csintro2/tilemap/intro.md
Replace `aka.ms` links with the direct source links for videos in CSIntro2.
**Note**:
>Some of the aka links that have replacement links still work, e.g.:
>
>https://aka.ms/40546a-array-sprite1
>
>Those links, however, were replaced with the new ones provided. If it's desirable to use the aka links, then I can roll those back.
RE: #2577
=> Replacement video links for CSIntro2

docfiles/script.html, docs/static/script-page.css
Various small optimization to pretify the shared script page:
Tested windows Chrome/Edge/FF. Needs to go in the arcade stable branch?
1366x768
1920x1080
mobile
Unclear why ipad sim does not resize to full width...
=> Share page tweaks

docs/tutorials/galga.md
The enemy sprites created in the `onUpdate()` event remain even though they leave the screen. Handling an ever increasing amount of sprite objects is a perf problem when played on hardware.
Fixes #2556
=> Make the Galga enemies auto destroy

docfiles/script.html
I'm making this directly to the stable branch as I have a separate, larger version of this change that I'm still finishing up; this is just a minimal change for now~
requires https://github.com/microsoft/pxt/pull/7707 to actually change anything, allows us to pass `?prebuilt=1` to the share page and have that propagate to run.html to fetch the prebuilt sim js
=> [stable1.2] propagate prebuilt flag to --run

pxtarget.json
re: https://forum.makecode.com/t/makecode-arcade-offline-pairing/5022/6, looks like they named their drives something novel and so we're not auto deploying to them.
For reference, this field is used in https://github.com/microsoft/pxt-electron/blob/master/src/deploy.ts#L90 to list out the drives / try to copy over the file to any matches
=> Fix kitronik arcade offline app deploy

docs/tutorials/chase-the-basketball.md
This should fix the issue we are seeing with the Space Jam tutorial where the Space Jam sprites aren't appearing on subsequent reloads.
Another work around for this is to always use incognito for each session.
This is a work around for an issue in microsoft/pxt stable6.2.
Here is where we chose which symbols to cache for a package:
https://github.com/microsoft/pxt/blob/stable6.2/webapp/src/compiler.ts#L669
notice we're comparing the symbol's `.pkg` field to the `name` variable.
The name var comes from the package config, e.g. "space-jam-sprites" in this case
The .pkg field comes from:
https://github.com/microsoft/pxt/blob/stable6.2/webapp/src/compiler.ts#L623
which is the directory name e.g. "spacejam".
So none of the symbols are matching and thus we're storing empty apis in the cache for …
=> fix sprites not appearing on spacejam tutorial

arcade.code-workspace
This is a development environment only change and has **no user impact**.
This sets a side bar color for the arcade workspace. this helps distinguish multiple VS Code windows at a glance.
Example:
=> Dev only: Set arcade VS Code workspace colors

pxtarget.json
Fixes https://github.com/microsoft/pxt-arcade/issues/2629
For now point to about in microsoft.com/makecode.
=> Changing arcade icon link to makecode.com

docs/concepts/breadcrumb-trail.md
Fix double declarations of `mySprite` in some snippets.
Fixes #2858
=> Fix sprite decls in 'Breadcrumb Trail'

docs/developer/sound.md
This covers the new waveforms added by https://github.com/microsoft/pxt-common-packages/pull/1177. 
(The old "metallic" tone was disabled a while back but not removed from documentation, I reused its number for the new "tunable noise" which as far as I can tell fills a similar role.)
=> Add new waveform descriptions to sound.md

docs/gamejams.md
Adds a quick ref page to link to the previous game jams / results.
=> add page linking to game jams

pxtarget.json
This fixes sound especially when using the big parallel screen
=> Bump codal on F4 to 1.3.0 - fixes sound choppines

docs/game-jam.md
Thumb images aren't generated for GitHub based projects. I had the game author add an image to their repo: https://github.com/UnsignedArduino/Fishy-Fishy-Cross-my-Ocean/issues/2.
Not sure if this is the best way to do this but it will fill the "gap" for now.
**Before:**
**After:**
Fixes #3044
=> Link in thumb image for 'Fishy Fishy' game

docs/skillmap/interface/activity1.md, docs/skillmap/story/story1.md
Travis recorded his sons Jackson and Noah playing through Skillmap. They found things that were easy fixes, so I've made the changes and I'll squash when tests pass.
- A formatted block name doesn't match the block
- Removed the word "shorthand"
- Remove the term **sprite editor** and call it **image editor** everywhere
=> Changed a couple of things based off feedback

targetconfig.json
Documentation has not been tested (because that's not possible right now). Every block is documented and has an example except for one ("set sound enabled", which needs no example).
I had to remove one block "move to tilemap location" because it relied on a dependency to @jwunderl's a-star extension which is not approved. I'll probably work with him to get it in at a future date. This extension is a bit different than riknoll/arcade-story because i've had time to iterate on the blocks since that extension was released. Feel free to try it out and let me know what you think.
Repo is here: https://github.com/microsoft/arcade-storytelling
Icon is this:
Blocks are these:
=> Adding microsoft/arcade-storytelling to approved extensions

package.json
Pulls in the change hardcoding the default URL for the skill map
=> [stable1.3] Bump pxt-core to 6.8.38

targetconfig.json
Adding a path alias to test https://github.com/microsoft/pxt/pull/7971
This maps this URL:
https://arcade.makecode.com/beta--skillmap#beginner
to this URL:
https://arcade.makecode.com/beta--skillmap#docs:/skillmap/beginner-skillmap-2
@kiki-lee is this the right skillmap to point to? We can change it before we "officially" release it, this is really just for testing.
=> Adding beginner skillmap path alias

docs/hardware.md
New link and product page for Ovobot Xtron:
https://www.ovobot.cc/en/product/detail/xtron-pro/
Fixes: #3177
=> Update link for Ovobot Xtron

docs/skillmap/intermediate-skillmap.md
Ran through the intermediate skill map, some quick fixes: adding completion nodes, removing old completionUrl, fixing interface tutorial link. This doesn't have the theming stuff, I'll make another PR whenever that comes in
=> Update intermediate skillmap to skillmap V2 syntax

docs/skillmap/intermediate-skillmap.md
Add the alternate source url for migrating user progress from the old (github) game maker guide to the new docs one.
=> Add pxt-skillmap-sample as an alternate source for the intermediate map

docfiles/script.html, docs/static/script-page.css
Fix the issues it ran into last time; here's it running on staging: https://arcade.staging.pxt.io/64715-80137-62241-32687 (theres a `HEAD_OVERRIDE` field set in staging at the moment making it reference this branch for docfiles, I'll remove that later today so it points to index-ref like normal). Main thing this change does is removes= one blocking web request (effectively just flattening the sim run code into the page so we don't have to wait to fetch that too). It also that it keeps the built js info in memory so if you switch to 'show code' and back it will be instant like Asphodel -- this is super helpful for me at least because I do that ALL the time when looking at forum games.
(I disabled the bit where it was preloading the simulator grayed out instead of showing the loading text …
=> Fix share page for release

docs/skillmap/intermediate-skillmap.md
Added these on accident, removing them!
=> Remove incorrect URL for game maker guide certificate nodes

docs/static/script-page.css
https://forum.makecode.com/t/game-controller-not-showing-up-on-mobile/6896
fix sizing for share page on safari; safari is very "by the book" on 100% height resolution (each parent element above must have height explicitly defined), so switch to flex to keep height consistent. Tested on safari / chrome / firefox / mobile safari / mobile android (chrome)
=> Fix share page sizing on mobile safari

docfiles/script.html
I went through a bunch of browsers on browserstack for the share page to make sure there weren't any other regressions and noticed this has been broken on old edge for a while (~4 months or so, since the asphodel ticks). Sounds like omitting this is technically a feature of es2019, but most browsers started supporting it long ago so only old edge hits it. Might as well fix anyway for cleanliness / we'll have another bug patch this week we can include it in anyways.
=> fix parsing for share page in edge17

docs/skillmap/collector/collector1.md, docs/skillmap/interface/activity1.md, docs/skillmap/platformer/activity1.md, docs/skillmap/puzzle/puzzle1.md, docs/skillmap/space/activity1.md, docs/skillmap/story/story1.md
Removing these, since the property only needs to be set in the skillmap markdown! Going to merge it in now, as the space and platformer tutorials are being linked in the live skillmap
=> Remove allowcodecarryover flags from tutorial markdown

pxtarget.json
turning on the tutorial info caching for these since the content seems relatively stable
=> Cache used blocks from space and platformer tutorials

docs/skillmap/space/activity4.md
this tutorial was loading without the status bars previously, and we would have cached the incorrect list of used blocks. small code change should invalidate that cache and cause the list to be re-parsed
=> Invalidate tutorial used blocks cache for Space Explorer activity 4

docs/static/gamejam/lib/gamejam.css, docs/static/gamejam/lib/gamejam.js, docs/static/gamejam/lib/gamejam.ts
based off the markdown hint style/wording! this should add it to every landing page
RE: https://github.com/microsoft/pxt-arcade/issues/3012#issuecomment-837257883
=> Add hint on gamejam landing page about expanding games

libs/color/pxt.json, libs/keyboard/pxt.json, libs/mouse/pxt.json, libs/palette/pxt.json, libs/radio/pxt.json, libs/storyboard/pxt.json
fix https://github.com/microsoft/pxt-arcade/issues/2391
These are the ones that stood out to me as 'unlikely to be what the user expects' or that are questionably functional
* mouse and keyboard: these are for making hardware devices act as mouse and keyboard, several times have had people on the forums confused / trying to use it to read input
* color and palette; these are more underlying libraries / mainly for compat with adafruit
* radio; questionable whether things work
* storyboard; js only and a bit confusing
=> make a few of the builtin exts searchOnly

package.json
pxt and pxt-common-packages versions are a bit out of date in arcade/beta right now so bumping.
=> bump pxt 6.13.54->7.1.4, pxt-common-packages 8.9.14->9.1.1

docs/concepts/sunday-drive.md, docs/concepts/throw-a-bone.md, docs/tutorials/lemon-leak.md
A few tutorials had nonconforming default parameters for **sprites.createProjectileFromSide(image, 50, 50)**.
Fixes #2049
=> Set current default parms for tutorial hints

docs/javascript-games/ping.md
fix https://github.com/microsoft/pxt-arcade/issues/3722
We had a bug before that destroyed sprites were still counted in `sprites.allOfKind` until the destroy effect was completed, which we were working around here with an extra flag on the sprite. Now that that bug is gone, it was crashing because there are times when no ball would be 'in play' temporarily
=> Fix crash in ping!, remove now unnecessary data flag

docs/skillmap/sc/sc6b.md
This snippet was using non-exported members of the characterAnimations namespace. To fix it, I made these changes:
1. Replaced the implementation with a call to the original function
2. changed the type of "rule" to "number" instead of "Rule" (Rules are actually numbers)
=> Don't use private namespace locals in tutorial customts

package.json
Bump to pick up new pxt ref in pxt-common-packages to update the transitive dependencies
=> bump pxt common packages to 9.2.7

docs/hour-of-code-2021.html, docs/static/hour-of-code/2021/styles.css
i'm not going to do it for this year but i'll file an issue for (after HoC) moving this header bar into a separate HTML file so that we can use it for docs pages that don't use the shared docs template
@soniakandah happy to make any changes!
=> Add header bar logos and styles to HoC page

docs/gamejam/global-2021.html, docs/hour-of-code-2021.html, docs/hour-of-code/educators-2021.html
new tick events across the three pages:
- `hourofcode2021.video.open`
- `hourofcode2021.video.close`
- `hourofcode2021.educator.learnmore.link`
- `hourofcode2021.educator.learnmore.button`
- `hourofcode2021.educator.forum`
- `hourofcode2021.gamejam.submit`
- `hourofcode2021.gamejam.skillmap`
- `hourofcode2021.gamejam.hoc`
- `hourofcode2021.gamejam.training`
- `hourofcode2021.gamejam.box`
@soniakandah @ElizabethRiffle please let me know if you add any more links or buttons (anything the user can click), otherwise i think we're set on telemetry!
for https://github.com/microsoft/pxt-arcade/issues/4179, will close the issue after this change goes in and i classify the new tick events
=> Final pass over tick events for hour of code, educator, and game jam pages

docs/static/gamejam/jams/time/info.json
fixes https://github.com/microsoft/pxt-arcade/issues/4425
just re-shared the games with thumbnail/gif capture this time!
=> Update broken thumbnails on time jam page

package.json
attempting to fix the "Payload too large" error in the npm publish build step! this drops our package size from 200mb to like 70
=> Ignore GIFs when generating npm package

docs/hero-banner.md
It should have been `banners` not `banner`.
I'll squash when tests pass.
=> Fixed typo with hero banner

docs/skillmap/sc/sc5.md, docs/skillmap/sc/sc6.md, docs/skillmap/sc/sc6a.md, docs/skillmap/sc/sc6b.md, docs/skillmap/sc/sc7.md, docs/skillmap/sc/sc8.md
The package name for the `arcade-character-animations` was incorrect.
`pxt-characterAnimations=github:microsoft/arcade-character-animations/`
-- corrected:
`arcade-character-animations=github:microsoft/arcade-character-animations/`
Fixes #3874, maybe.
I couldn't test this in the actual skillmap as my local serve crashed when trying to retrieve partner content for the splash.
Currently, help for the 'override' (`loopFrames2()`) of the character animation `loopFrames()` block isn't working.
The help from the base extension itself IS working though:
We'll see if correcting the name fixes it. 🤞
=> Corrected package name 'sc' skillmap animations

docs/courses.md, docs/projects.md
close https://github.com/microsoft/pxt-arcade/issues/4653
Note this page is used to generate both the homescreen carousel & is the /courses page so it completes both parts mentioned in the issue~
=> update courses to remove cs intro series from home screen

docs/concepts/which-button.md
The 'on any button' text still persists on this page. Change 'any' to 'A'.
Fixes #2360
=> Fix block highlight text in 'Which Button' activity

package.json
Includes these two fixes:
1. Fix for the collision bug for sprites where sprites get caught on tiles above them (https://github.com/microsoft/pxt-common-packages/commit/8293dac2025066d3141f32a76d9478ac57596016)
2. Fix for a couple of tilemap bugs around the load/unload events (https://github.com/microsoft/pxt-common-packages/commit/1c465ea78165960c21c5eba2ec60f0792e4923c0)
=> [Stable 1.8] bump common packages to 9.4.13

docs/courses/csintro2/arrays/sprites.md
In example 2b, the page shows, in the repeat 30 times block, the firework.ghost flag being set to true. But that should be the projectile.ghost flag, correct? The firework was already set to a ghost in the start block
=> Swapped projectile for firework

docs/GameList.json, kiosk/public/GameList.json
re: https://github.com/microsoft/pxt-arcade/commit/0c0a075bbaf33cd570b640160856c21505c1debb, fix json & ran npm run deploy.
I guess there's no real need to run `npm run deploy` for this file as it just gets copied directly over... but at least worth pulling locally and testing before sending off so that works. I swapped the old version of pxt-kickoff I gave Jacqueline with a version that lets you pick which teams will play: https://arcade.makecode.com/99776-77448-58171-80239 (and e.g. handles setting alt colors if the same team is set for both sides).
@riknoll one thing that might be nice for menu extension would be something like 'reset scroll' -- I have it graying out the selected player team in the background while you select opposing team, and I lock to scroll speed 0 so it's not as …
=> Bump kiosk game list

package.json, scripts/copyArcadeSim.js
Previously you had to install rimraf to run the copyArcadeSim script. This removes that secret dependecy now that node's fs lib supports recursively deleting directories.
Also added an npm script for convenience
=> Remove rimraf depdency

docs/courses/introcs.md
Fix link to https://makecode.com/github-teacher-verification; the parsing is messed up so it counts the ) as part of the link and points at `https://makecode.com/github-teacher-verification)`
@ElizabethRiffle ^^ here's the fix, will take up to a day to clear cloud cache
=> fix gh-teacher-verif link

kiosk/src/App.tsx, kiosk/src/Models/Kiosk.ts
Adds a secret URL argument for opening any shared game in the kiosk experience. This works just like the pub URL argument in the editor:
```
https://arcade.makecode.com/kiosk#pub:xxxxx-xxxxx-xxxxx-xxxxx
```
The short form share id also works!
Using this argument will bypass the main menu and open the game directly in the kiosk game player. It also blocks you from escaping back to the main menu, so it's ideal for kiosk scenarios where you only want a single playable game.
The high score/leaderboard part of the kiosk is not supported in this mode
=> Add pub hash to kiosk to open any share game

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpush.yml, package.json
Follow up of https://github.com/microsoft/pxt-arcade-sim/pull/70 to pick up changes that make canvas usable with screen reader.
=> upgrade to sim with nvda support

docs/hour-of-code-2022.html
with target="blank" it's currently opening in the same tab as it's a named target instead of just 'new tab' opt -- e.g. if you click a skillmap, then go back to hour of code page and click twitch icon, the skillmap tab will go to twitch.
=> _blank so hoc2022 buttons don't all open in same window

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpush.yml, package.json
The latest arcade-sim introduced a regression **only when pointer-events is enabled**. Basically preventing the event bubbling breaks selecting the canvas using the mouse.
https://github.com/microsoft/pxt-arcade-sim/commit/148e538b56ae70d8c93c756becf4b5cef601118d
=> bump to arcade-sim v0.9.7

theme/site/globals/site.variables, theme/style.less
Fixes https://github.com/microsoft/pxt-arcade/issues/5058
I definitely prefer the orange of the micro:bit music category but this looks okay too
=> match sound effect editor colors to music category

targetconfig.json
Fixes https://github.com/microsoft/pxt-arcade/issues/5079
=> Update shortcuts for mole & balloon skillmap.

targetconfig.json
closes https://github.com/microsoft/pxt-arcade/issues/4944 -- i fixed tutorial approval in https://github.com/microsoft/pxt/pull/8977 so will only work after the next release (but will work in beta after this pr).
I suppose it might be worth adding a `tutorial-repo` flag in RepoData interface https://github.com/microsoft/pxt/blob/master/localtypings/pxtarget.d.ts#L52 so that tutorials only extensions don't show up in search, but that's pretty minor as they'd have to be searching for that extension's keywords in the first place. then when we get more approved external tutorials we can reuse the extension page for a tutorial search page if we wanted~
one of the tutorials https://arcade.makecode.com/beta#tutorial:code-ninjas-home-office/game-building-session-tutorials/find-the-ninja
=> Add code ninjas tutorials as approved content

docs/courses/introcs.md
Remove the Professional Development Opportunity note from the CSP page now that its date has past.
Closes #5095
=> Remove PD opportunity note

docs/skillmap/balloon/balloon4.md, docs/skillmap/mole/mole1.md, docs/skillmap/mole/mole2.md, docs/skillmap/mole/mole3.md, docs/test/skillmap/balloon/balloon4.md, docs/test/skillmap/mole/mole1.md, docs/test/skillmap/mole/mole2.md, docs/test/skillmap/mole/mole3.md, docs/test/skillmap/mole/mole4.md
This is mostly an FYI, even though it touches non-test files.
Accidentally used img'.' instead of img`.`, which messed up my default blocks.
=> Removed titled img references

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpush.yml, package.json
Just 3 check-ins between 0.9.8 & 0.10.3 -> https://github.com/microsoft/pxt-arcade-sim/commits/master seems ok to just point the latest.
If you think it is risk, I can port to the 0.9 stable channel in arcade-sim before I port here.
=> Bumping arcade-sim 0.10.3

docs/test/skillmap/balloon.md
Turning on the option to have the multiplayer share callout appear in the completion modal for the balloon skillmap
=> Add showMultiplayerShare to balloon test skillmap

docfiles/script.html
PR 3 of 3 for automatically detecting if a game is multiplayer at compile time.
This PR relies on https://github.com/microsoft/pxt-common-packages/pull/1381 and https://github.com/microsoft/pxt/pull/9161
Adds a multiplayer button to the share page. Currently looks like this:
...and could obviously do with a design pass. The button shows up as soon as the compile has finished. If we eventually end up moving the compile to the server side, we need to make sure this metadata is sent down (@aznhassan FYI)
=> Add multiplayer button to the share page

kiosk/src/Components/AddingGame.tsx
In production, when scanning the QR code, the path wouldn't fully resolve itself because of how I coded the URL into the qrcode generator. I changed the production path to fully include arcade.makecode.com so scanning the qr code reaches the correct endpoint.
=> Kiosk: using full path for scan endpoint

kiosk/src/App.tsx, kiosk/src/Components/GameList.tsx, kiosk/src/Models/Kiosk.ts
In a classroom setting, we might not want the kiosk to be populated with the games that we have from the game list. We should allow the kiosk to only be full of students' games.
Now, if you use the --clean flag in the url, the kiosk will be completely empty until games are added.
If you get rid of the flag, the games from the game list and the games that the users have added will be on the kiosk. 
Needed for @kiki-lee's classroom visits this week.
=> Kiosk: clean state for kiosk, will not use game list

docs/projects.md
Just pushing this automatic update since the Wakanda Forever tutorial was moved to the beginning of the tutorials carousel.
=> update projects.md with Wakanda Forever tutorial

package.json
bumping to pick up custom multiplayer user icons / reactions changes (+ others)
(and here's one of the test programs that sets a few icons https://arcade.makecode.com/S53662-77802-01315-54005)
=> bump pxt-common-packages > 10.3.5, pxt-core > 8.5.7

pxtarget.json
Needed to add this field so that the share to kiosk button would not be available on micro:bit and Minecraft targets. 
Tied to https://github.com/microsoft/pxt/pull/9297
=> Share to kiosk field added to app theme in pxtarget.json

package.json
pick up multiplayer changes, notably enabling XOR diff which we have to test a bit further
=> bump pxt->8.5.16, pxt-c-p->10.3.8

targetconfig.json
Depends on https://github.com/microsoft/pxt/pull/9328
Closes https://github.com/microsoft/pxt-arcade/issues/4992
I also added more tags for both the builtin extensions and the approved repos.
=> Categorize builtin extensions in the extension browser

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpush.yml, package.json
pick up https://github.com/microsoft/pxt-arcade-sim/pull/86
I guess it's probably fine either way to port this or not unless you have a preference @eanders-ms ? as they can just use `/beta--run?id=...`
=> bump arcade sim to v0.11.1

docs/kiosk.html, kiosk/public/index.html
We don't want the description for kiosk to be the default "create-react-app" phrase. The updated text is similar to what is said in the kiosk docs.
=> Kiosk: new description in the index html file

libs/sevenseg/docs/reference/sevenseg.md
Include the top level `./reference/sevenseg.md` page as a destination for the "Learn More" line in Extensions.
Closes #5580
=> Add main reference page for 'sevenseg`

pxtarget.json
It has 3 parts for every language: 
1.	UI:       Editor UI strings (like new project or tutorial text ). This is common across all the editors we have. 
2.	Core:  All the core blocks which are loaded with the default project. This one is the most import one. 
3.	Blocks:  These are additional blocks such as servo, but also include some of the microbit specific strings for download etc.  
1st & 2nd one is the most important. 
context	| language | 	translated% |	approved%	| phrases |	translated|	Approved
---|---|---|---|---|-------|---|
ui |	ar |	91%	| 46% |	1923 |    	1767 |    	900
core | 	ar |	51%	| 51%	| 56     | 	29	| 29
blocks	| ar |	32%	| 28% |	6526 |    	2113 |    	1831
I see only 51% in core strings.  This is just one file in the attached.
2925	arcade/core-strings.json	ar	56	29	29 …
=> Enable arabic in /beta

docs/js-templates.md
These will be consumed by my upcoming VS Code extension changes. They're defined as a gallery, but won't be in the homescreen. We can choose to surface them later if we feel like it.
=> Add project templates for VS code extension

docs/multiplayer-games.md, pxtarget.json
@jwunderl do you know if this will this work?
When I click a multiplayer launch url, I want it to open on the current domain, which might be staging, a custom target, or the production site, etc.
=> Use relative urls for multiplayer launch points

docs/multiplayer-games.md
Remove leading `/` in the `sharedExample` URL form for the `otherActions` entry of each gallery game.
Closes #5868
=> 'Open in Editor' URL fixes for multiplayer gallery

docs/hero-banner.md
Now that we're deprioritizing the "beginner" skillmap, I'd like this banner to point to the "Intro" tutorial.  We can use the same art (it actually works better with this than with the previous selection.)
=> Removing beg skillmap from banners

pxtarget.json
This addresses the issue mentioned in this comment: https://github.com/microsoft/pxt-microbit/issues/5167#issuecomment-1555362780
Makes use of the existing hideReplaceMyCode flag: https://github.com/microsoft/pxt/blob/master/webapp/src/components/tutorial/TutorialContainer.tsx#L273
=> Hide "Replace my Code" unless we're in a skillmap

docs/skillmap/forest_new/forest1.md, docs/skillmap/shark/shark1-simple.md
Mention moving to the **Next** step instead the using the obsolete "instructions tab".
Closes #5918
=> No 'instructions tab' in skillmaps

package.json
Should be fine as no one should be consuming docs this way (you would usually clone or fork repo). Worth noting https://github.com/microsoft/pxt-arcade/pull/4515 was removing .gifs before but now that's not working; maybe a weird regression in files field parsing in node 16 since I bumped that recently (https://github.com/microsoft/pxt-arcade/pull/5940/files)?
=> try omitting docs from upload

editor/extension.ts
Fix the cases that seemed relevant with https://github.com/microsoft/pxt/pull/9611, so we can port it without breaking too many people and fix things like https://forum.makecode.com/t/error-when-using-makecode-arcade-in-google-chrome/21210/4
This should handle swapping them back, though will want to test in stable just to double check. I found the ones that were problematic here using the logs that I added when we get translations that are rejected, so these are the ones that were valid in live but caught as invalid in beta
=> upgrade rule to fix invalid translations in hot fix

docs/game-jam.md, docs/gamejam/prehistoric.html, docs/projects.md, docs/static/gamejam/jams/prehistoric/info.json, docs/static/gamejam/jams/prehistoric/rules.md, docs/static/gamejam/lib/gamejam.css, docs/static/gamejam/lib/gamejam.js, docs/static/gamejam/lib/gamejam.ts
This PR does the following:
1. Adds the game jam winners to the prehistoric jam page
2. Fixes a few CSS oddities for the winners section of said page
3. Replaces the time jam carousel on the home page with the entries from this jam
=> Add game jam winners

kiosk/src/Components/GameList.tsx, kiosk/src/Components/GameSlide.tsx
When locking the kiosk, the "add game" button would disappear, but the "delete game" button would still be under user-added games. We want the UI to be consistent, so the delete button should go away as well. Because it is locked the user won't be able to navigate down to the button if they try, but this will make the kiosk seem broken since the button is still visible.
Closes https://github.com/microsoft/pxt-arcade/issues/6015
=> Kiosk: Making delete button disappear when locked

package.json
no code change, just trying a rebuild; guess from richard and I is roughly that the 'once in a blue moon vs/editor/editor.main.css file change' happened during CI and caused something to break, see 1.12.39 in built repo. The result is that the cached codicon.ttf is returning the css file for some reason. Seeing if this rebuild works for now and we can see if we can backtrack to the 'why'
=> [stable1.12] bump to 8.5.52

libs/hw---n4/pxt.json, pxtarget.json
re: https://github.com/microsoft/pxt-arcade/issues/6070
=> enable n4 hardware

targetconfig.json
Duped content from https://github.com/microsoft/pxt-arcade/blob/master/docs/hardware.md, we want to avoid having dep on markdown page / just targetconfig.
RE: https://github.com/microsoft/pxt-arcade/issues/6070
localization will need to be handled similar to https://github.com/microsoft/pxt/pull/9688, but that's fine / easier to explain than the json in md that currently exists.
=> port hardware options to targetconfig

docs/tutorials/globetrotters.md
Adding a "starter project" tutorial for the Globetrotters team in case the full tutorial doesn't materialize by Monday.
=> Starter project for globetrotters

libs/hw---n3/pxt.json, libs/hw---n4/pxt.json
As quick follow up for https://github.com/microsoft/pxt-arcade/pull/6117, to swap the default hardware entry that shows up
=> set n4 back to experimental, enable n3

libs/hw---n3/pxt.json, libs/hw---n4/pxt.json, targetconfig.json
porting https://github.com/microsoft/pxt-arcade/pull/6117, https://github.com/microsoft/pxt-arcade/pull/6118
I think they microbit builds will be elided when targetconfig swaps to new one as n3 was still marked disabled until this is merged / bumped
=> [stable1.12] Cherry pick n3/n4 fixes

docs/kiosk-data/GameList.json, docs/projects.md, package.json, targetconfig.json
Companion PR in pxt: https://github.com/microsoft/pxt/pull/9723
=> Move kiosk game list to targetconfig.json

targetconfig.json
Resolves https://github.com/microsoft/pxt-arcade/issues/6153
=> updated kiosk built-in games

docs/arcade-devices.md, docs/hardware.md, targetconfig.json
The MRT Maker Kit card was left out of the "Arcade Compatible Devices" gallery in #6198.
Closes #6214.
=> MRT maker kit added to compat devices

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpush.yml, editor/tsconfig.json, package.json
part 2 of the fix for the recent build break.
see part 1 here: https://github.com/microsoft/pxt-arcade-sim/pull/106
=> exclude type roots from editor build

docs/eval-ref.json, package.json
This should allow /eval to redirect to /--eval.
Pxt-core bump is needed to get teacher tool content from pxt.
=> Add Teacher Tool Eval URL Redirect (and bump pxt-core to 9.3.9) 

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpush.yml, libs/browser-events/pxt.json, package.json, pxtarget.json
This PR requires https://github.com/microsoft/pxt-common-packages/pull/1467
The build will fail until that is merged.
Adds the browser events extension to the extension list.
=> Add browser events extension

libs/shader/pxt.json, libs/shader/shims.d.ts, pxtarget.json
Somehow this commit was made on the stable branch but not master! I was wondering why my screen transitions extension only worked on the released arcade...
=> include shader in build

pxtarget.json
We might want to look into a different and more "sticky" pattern for this because if we do the styling this way, we'd have to define this flag in each target. I wasn't sure if there was a way to define url query parameters like this universally without the backend.
=> Teacher tool: added styling for teachertool=1 url flag

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpush.yml, editor/tsconfig.json, package.json
Pick up https://github.com/microsoft/pxt/pull/9812 and https://github.com/microsoft/pxt/pull/9792 (and it's corresponding change in common-packages) https://github.com/microsoft/pxt-common-packages/pull/1461
Cherry-pick: exclude type roots from editor build (https://github.com/microsoft/pxt-arcade/pull/6274)
=> Bump pxt-core -> 8.5.59 and common-packges -> 10.3.24

docs/hardware.md
I do need approval on this one since it touches the arcade homepage...
Now that we have three different types of cabinets, we're directing the card on the home page to open a page with all three options.
=> Changing cabinet homepage card

docs/gamejam/female-gamechangers.html, docs/static/gamejam/jams/female-gamechangers/rules.md
When showing this off today, we got some feedback that Women's history month was sort of buried in the copy. This PR moves it up and makes it bold:
=> Move women's history month higher up in the copy

package.json
Bumping core to get the image default values fix https://github.com/microsoft/pxt/pull/9909
=> bump pxt-core to 8.5.60

libs/hw---n3/config.ts
fix for https://github.com/microsoft/pxt-arcade/issues/3699
=> add mapping for edge connector for N3

docs/hardware/dbg.md
This PR addresses some outdatedness in one of the guides you host which has come to the attention of the project which is reference (Black Magic Debug). Please see the updated project repository link in the changes for this PR.
Fair and full disclosure: we are the lead maintainer for the project, however we can certify that the old link was taking people to a wiki that no longer exists and to a GitHub organisation which has nothing to do with the project any more and that the new link points to the current home of the project.
If the link should be to the project's website rather than code repo, we can switch the links over and point it to black-magic.org which is the main website for the project now.
=> Update the repo link for Black Magic Debug

pxtarget.json
A temporary measure while we upgrade to the v2 apis
=> Temporarily disable upload docs

docs/games.md, docs/jr-tutorials.md, docs/skillmap/educator-info/dino-map-info.md, docs/skillmap/educator-info/racer-map-info.md, docs/test/tutorials/bubbles.md, docs/tutorials/target.md
@riknoll - Do I still need to do this?  I was able to see the games.md page already...
=> Adding pages for Summer games (#6393)

docs/test/skillmap/forest/forest2.md, docs/test/skillmap/forest/forest3.md, docs/test/skillmap/forest/forest4.md, docs/test/skillmap/forest/forest5.md, docs/test/skillmap/forest/forest6.md, docs/test/tutorials/bubbles.md
Cherry-picking the forest and bubble fixes so we can test them.
=> Fixes for Forest and Bubble (#6405)

docs/courses.md
The GameGo cards were missing the `cardType` field.
Closes #6402
=> Add card type to GameGo cards

docs/hardware.md
Splitting the hardware section to boards and shields. Let me know if looks ok
=> Add separate section for shields

docs/beginner-maps.md, docs/skillmaps.md, docs/tutorials.md, pxtarget.json, theme/site/globals/site.variables, theme/site/views/card.overrides, theme/style.less
Arcade's orange does not allow for accessible contrast. We could try to darken it, but that would not create a desirable color, so we've decided to update the arcade theme.
Fixes https://github.com/microsoft/pxt-microbit/issues/5469
Fixes https://github.com/microsoft/pxt-arcade/issues/3973
Fixes https://github.com/microsoft/pxt-microbit/issues/5465
Please play around with this! I think it will be good to use a testing session for everyone to get a feel with it, but there are a lot of spots that have different styling, so there might be something that I missed. Note that the "New? Start Here" labels are orange right now because the color is changed in docs. https://arcade.makecode.com/app/3e33481bd3886ff462d55b14af25a3360e2a0402-0e60e79eaf#
=> Accessibility compliance: editor colors update

docs/beginner-maps.md, docs/skillmaps.md, docs/tutorials.md
I changed the "New? Try This!" banners to be the purple color for the color updates for arcade, but since these changes are in docs, the change is live. We need the color to go back to orange for now.
=> Color update: put the new try this banners back to orange

package.json
The changes that will take effect are outlined in these PRs: 
In pxt: https://github.com/microsoft/pxt/commit/0425ce8e836b700256a54b27b0ea83b46067cf79
In common packages: https://github.com/microsoft/pxt-common-packages/commit/1c2be247ea57f7718604daa94e69707b07e635b5
=> [stable1.12 hotfix] bumping pxt-core, common-packages for user high scores on kiosk

docs/publishing-games.md
Noticed this in livestream. The features in this page are no longer in beta.
=> Remove outdated share "beta" note

docs/tutorials/galga.md, docs/tutorials/simple-extensions.md
The "Simple Extension" tutorial was referring to `corgi.follow()` instead of the updated api of `corgi.cameraFollow()`, see #4820.
The "Galga" blocks tutorial mentioned the sprite position block using parameters of `vx` and `vy` rather than `x` and `y` as it should have.
=> Fix mismatch errors for block names in tutorials.

docs/developer/local-cpp.md
This is a little cryptic but I think much better than nothing.
cc @tballmsft
=> Write down how to build C++ locally

docs/skillmap/mole/mole1.md
Thanks for this amazing project!
I caught this tiny typo while reading through the tutorial with a 2nd grader.
=> Fix typo on part 1 of whack-a-mole tutorial

docs/concepts/bouncing-burger.md, docs/concepts/picnic-food.md, docs/concepts/princess-pizza.md, docs/concepts/setting-the-scene.md, docs/concepts/sunday-drive.md, docs/concepts/throw-a-bone.md, docs/concepts/walking-hero.md, docs/concepts/which-button.md
Since the sidedocs view wants to stick `doc:` in here, the simple thing to do is to just remove the "Open this as a tutorial in the editor" links.
Otherwise, we can change the sidedocs open link logic. It currently does this:
`https://arcade.makecode.com/---docs#doc:#tutorial:/concepts/walking-hero`
Closes #6604
=> Remove open as tutorial links

editor/extension.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6616
this adds two upgrade rules for very old projects and fixes an exception in another. the new rules are explained in the comments
this has actually been broken for a long time, but new blockly has surfaced the errors. old blockly used to be looser with field validation so it wouldn't overwrite invalid field values when the workspace loads, even though it wouldn't render correctly. for example, if you open the project in the linked issue in live you'll see that all of the blocks setting the `Sprite.z` property actually say `x`, but they still compile to `z` because the invalid value isn't overwritten.
new blockly doesn't allow invalid field values in dropdowns, and instead defaults to choosing the first available item in the list of …
=> add upgrade rules for legacy animations and setter for z

theme/site/globals/site.variables, theme/style.less
replaces share tech mono with the standard microsoft font string. no more annoying monospace font!
look how much better it looks:
=> remove share tech mono

editor/extension.ts
requires https://github.com/microsoft/pxt-common-packages/pull/1495
pretty self explanatory! just adding an upgrade rule that adds the new fields to the prompt for number/string blocks
=> Add upgrade rule for new system keyboard APIs

pxtarget.json, theme/color-themes/arcade-dark.json, theme/color-themes/arcade-legacy.json, theme/color-themes/arcade-light.json, theme/color-themes/overrides/arcade-dark-overrides.css, theme/site/globals/site.variables
The most notable change here is setting the default arcade theme to legacy instead of light. It also adds the neutral base color to all themes and includes some fixes to dark theme.
Somewhat counter-intuitively, I've updated the Semantic UI blue color as well. This affects our notification popups. Normally I'd switch these to use the theme's colors, but one of the notifications is "Sign-in successful", and signing in also triggers the theme to change based on the user's preferences. The result is that the notification switches colors halfway through, which looks odd. So for now, I decided to just let this fallback on the non-themed color instead, but it required a color update to be easily readable.
Fixes https://github.com/microsoft/pxt-arcade/issues/6751
=> Arcade Theme Fixes

editor/extension.ts
fixes https://github.com/microsoft/pxt-arcade/issues/6677
see https://github.com/microsoft/pxt-arcade/pull/6668 for an explanation; this bug only affects ancient projects and is actually broken in live as well (though less so, it still compiles correctly just doesn't show the right value in the block)
=> Upgrade SpriteKindLegacy in very old projects

theme/color-themes/arcade-dark.json, theme/color-themes/arcade-legacy.json, theme/color-themes/arcade-light.json, theme/color-themes/overrides/arcade-light-overrides.css
The secondary-accent color was previously only used for the "cloud projects" card, but with https://github.com/microsoft/pxt/pull/10424, we now use it for the active sim toolbar buttons instead. As a result, having a darker shade instead of a lighter shade feels more natural.
Meanwhile, the "cloud projects" card can just use the normal secondary color, but arcade-light needs an override, since in that theme, primary = secondary.
Upload target: https://arcade.makecode.com/app/a2b90411277dc31bf416b4bc830035728af40d75-0cd92e0a68
=> Update Secondary Accent Colors for Arcade

docs/tutorials/chase-the-pizza.md
The single dot image spec in `sprites.create()` no longer implies the default 16x16 empty image. So, define an empty 16x16 image explicitly.
````
```blockconfig.local
let pizza = sprites.create(img`.`, SpriteKind.Player)
```
````
Closes #6349
=> Use default image size in 'Chase the Pizza'

pxtarget.json, theme/color-themes/arcade-dark.json, theme/color-themes/arcade-light.json, theme/color-themes/arcade-orange.json, theme/color-themes/overrides/arcade-dark-overrides.css
Fixes https://github.com/microsoft/pxt-arcade/issues/6814
- Rename themes to remove "Aracde" (i.e. "Arcade Light" -> "Light")
- Rename "Legacy" to "Orange" (normally, we shouldn't change ids, but since it hasn't shipped yet, I think it's fine for now)
Fixes https://github.com/microsoft/pxt-arcade/issues/6813
- Change language headers to white instead of teal
Fixes https://github.com/microsoft/pxt-arcade/issues/6807
- Do not apply the dark-theme inverted button override to teaching bubble buttons
- Depends on pxt change to add ids (https://github.com/microsoft/pxt/pull/10436)
Upload target: https://arcade.makecode.com/app/806ccd6ac700307751a9a55c0f3bdd0143e45dd4-5c060effad
=> Theme Renaming and Fixes

docs/concepts/star-field.md
The `set projectile to` block highlights open the `Variables` toolbox category by default. Change them to open the `Sprites` category where the block will be to select.
Closes #6325
=> Set 'opening' category to sprites in Star Field tutorial

.github/workflows/pxt-buildmain.yml, .github/workflows/pxt-buildpush.yml, editor/extension.ts, package.json
fixes https://github.com/microsoft/pxt-arcade/issues/6810
this updates the upgrade rule so that we now expand the ask for string/number blocks and set the onScreenKeyboard option to true when upgrading older projects.
for example, this project from live:
will upgrade to this project:
12 and 6 are the default values for the answerLength parameter
=> Update "ask for string/number" upgrade rule to reflect new default parameter

docs/tutorials/snow.md
Seems that the variable `anim` has too many assignment declarations in the tutorial config code. Was causing the `anim` variable inside `add animation` to have the `anim2` name.
Closes #6284
=> Variable 'anim' is over declared in 'Snow Globe`

theme/color-themes/overrides/arcade-dark-overrides.css
Needed so the buttons in blockly workspace search are visible after https://github.com/microsoft/pxt/pull/10448
=> Invert images for the dark theme workspace search buttons

theme/color-themes/overrides/arcade-dark-overrides.css
Port of https://github.com/microsoft/pxt-arcade/pull/6850 (https://github.com/microsoft/pxt-arcade/commit/89bec11852fb7a9b87c7bdb8e5044c5d38741938)
=> Port to Stable: Invert images for the workspace search buttons in dark theme (#6850)

docs/tutorials/blazing.md
Remove the comments from `blockconfig` in the tutorial so they won't appear in the toolbox blocks.
Closes #6852
=> Remove comments from 'blockconfig' in 'Blazing Glory' tutorial

package.json
This reverts commit f00c6f6970d78fa9df0dfbef8107e10f67a11a32.
=> [stable2.0] Revert "bump pxt-core to 11.3.57 and pxt-common-packages to 12.2.14"

package.json
__Do not edit the PR title.__
It was automatically generated by `pxt bump` and must follow a specific pattern.
GitHub workflows rely on it to trigger version tagging and publishing to npm.
=> [pxt-cli] bump version to v2.0.55

package.json
bumping core to get the changes for pixelating the skillmap background
=> [stable2.0] bump pxt-core to 11.3.61

package.json
bumping the version for the emergency hotfix
=> [stable2.0] bump pxt-core to 11.3.63
