- TODO.md
- docs/examples/asteroids.md
- docs/examples/car-race.md
- docs/examples/duck.md
- docs/examples/mega-bounce.md
- docs/examples/runner.md
- libs/game/game.ts
- libs/game/hud.ts
- libs/game/pxt.json
- libs/game/sprites.ts
- package.json
> Refactoring hub/sprites

- TODO.md
- docs/examples/asteroids.md
- docs/examples/car-race.md
- docs/examples/duck.md
- docs/examples/jumper.md
- docs/examples/mega-bounce.md
- docs/examples/runner.md
- docs/examples/snake.md
- libs/game/game.ts
- package.json
- sim/simulator.ts
Moving frame under game.frame to keep this logically grouped.
> Game.frame

- docs/examples/duck.md
- libs/game/game.ts
- libs/game/hud.ts
- package.json
- sim/simulator.ts
- sim/tsconfig.json
> Support for highscore

- docs/examples/asteroids.md
- libs/game/sprite.ts
Sprites die away after a number of game iterations.
> Support for lifespan in projectiles/particles

- docs/examples/turtle.md
- docs/examples/turtle/spiral.md
- libs/core/base.ts
- libs/core/pxt.json
- libs/turtle/pxt.json
- libs/turtle/targetoverrides.ts
- libs/turtle/turtle.ts
- pxtarget.json
- targetconfig.json
A mini turtle library built on top of the sprites
> turtle library

- libs/device/pxt.json
- libs/keys/keys.ts
- libs/keys/pxt.json
- libs/keys/targetoverrides.ts
- pxtarget.json
- update-common-packages.sh
- renaming input package to keys to match namespace
- adding targetoverrides to redefine available buttons
> moving input to keys project

- docfiles/script.html
Page is identical to one in pxt, except for comment (for testing).
> Testing custom script page

- docfiles/script.html
Nothing major, just making the content of the script page take up more of the screen. 
Will do more of a re-design and optimize later.
> Make the script page wider

- docfiles/abuse.html
- docfiles/script.html
- docfiles/scripthead.html
- sim/public/sim.css
- sim/simulator.ts
Trialing the new share page with this editor. 
Update simulator sizing and new share page.
> New share page

- libs/screen/targetoverrides.ts
> Adding block identity for image buffers

- libs/screen/targetoverrides.ts
- package.json
Needs https://github.com/Microsoft/pxt-common-packages/pull/279
> moved to common

- theme/style.less
> Use pxtsemantic

- docs/examples.md
- docs/examples/guess-the-letter.md
> Adding an example for the prompt API

- libs/screen/targetoverrides.ts
> Fix image shim annotation

- package.json
> Bumping pxt-common-packages

- libs/core/ns.ts
- libs/device/ns.ts
- libs/screen/ns.ts
- pxtarget.json
Depends on https://github.com/Microsoft/pxt-common-packages/pull/317
> Update block colors.

- sim/simulator.ts
Don't scroll simulator with up / down arrow keys
Fixes https://github.com/Microsoft/pxt-arcade/issues/125
Fixes https://github.com/Microsoft/pxt-arcade/issues/39
> Don't scroll simulator with up / down arrow keys

- theme/blockly.less
Fixes https://github.com/Microsoft/pxt-arcade/issues/80
> Fixing the antialiasing of pixel images in image picker

- THIRD-PARTY-NOTICES.txt
This is template, please add the additional license
> adding third party notices file

- sim/controlPad.ts
- sim/public/sim.css
- sim/simulator.ts
Fixes https://github.com/Microsoft/pxt-arcade/issues/104
Fixes https://github.com/Microsoft/pxt-arcade/issues/64
Updated sim!
Now with:
* bigger buttons
* support for Edge/IE
* landscape layout
* better scaling
Tested in Chrome, IE, and Edge
> New new sim

- sim/gamepad.ts
- sim/simulator.ts
Tested with an Xbox controller. The following should be supported:
Xbox | Arcade
--------|--------
A | A
B | B
D-Pad/Left joystick | Directions
Start (hamburger on xbox) | Reset the game
@jamesadevine
> Gamepad support

- libs/device/docs/reference/game/reset.md
- libs/device/docs/reference/game/runtime.md
Add docs for **reset()** and **runtime()** which are local to this target.
> Game api ref for this target

- docs/SUMMARY.md
- docs/reference.md
> Add sprites to ref namespaces

- libs/corgio/README.md
- libs/corgio/corgio.ts
- libs/corgio/pxt.json
- libs/darts/README.md
- libs/darts/darts.ts
- libs/darts/pxt.json
- pxtarget.json
Adding in the extensions I wrote to use in the course; this allows for a fix for #260's snippets that fail the automatic testing (I'll just need to update them to refer to the the included files). In doing so, it also removes the external dependencies from the course (my repos).
* corgio (from [here](https://github.com/jwunderl/pxt-corgio)) is a corgi that handles 'platformer like' movement
* darts (from [here](https://github.com/jwunderl/pxt-darts)) projects the path it will travel onto the background (e.g. for making a golf game where it gives a hint on where you're going to hit the ball)
> Example extensions for intro courses

- targetconfig.json
Remove corgio and darts from the approved packages as they are in built package
> Cleanup approved repos

- docs/about.md
fixes [#297](https://github.com/Microsoft/pxt-arcade/issues/297)
> fix link to repo

- sim/api.ts
> Player two on keyboard

- docs/courses/SUMMARY.md
fix 0.0.108 failing travis, typo in courses/SUMMARY
> fix summary format

- docs/courses/csintro1/loops/project.md
- docs/courses/csintro1/motion/project.md
- docs/courses/csintro1/project/final.md
- docs/courses/csintro2/arrays/project.md
- docs/courses/csintro2/final-project.md
- docs/courses/csintro2/functions/project.md
- docs/courses/csintro2/logic/project.md
- docs/courses/csintro2/tilemap/project.md
Minor tweaks requested by the vendor who is making the MSIA OneNote.
@ganicke courses/csintro1 is mostly finished on our side, if you want to do a pass of edits on it at some point. The changes in this PR are fairly low priority so if you want to make the changes here that'd be fine, whatever works. 
(courses/csintro2 is also pretty much finished, but the OneNote isn't finished so there might be a bit more changes there)
> Course tweaks

- sim/api.ts
- sim/controlPad.ts
menu button triggers controller key 7.
> support for menu btn events in sim

- package.json
- pxtarget.json
depends on https://github.com/Microsoft/pxt-common-packages/pull/482
> Use new codal's version as required by new pxt-common-pkgs

- docs/courses/csintro1/loops/project.md
- docs/courses/csintro1/motion/project.md
- docs/courses/csintro1/project/final.md
- docs/courses/csintro1/review/asteroid-blaster.md
- docs/courses/csintro1/review/baseball-catching.md
- docs/courses/csintro1/review/dodgey-duck.md
- docs/courses/csintro2/arrays/project.md
- docs/courses/csintro2/arrays/sprites.md
- docs/courses/csintro2/arrays/string.md
- docs/courses/csintro2/arrays/tilemap.md
- docs/courses/csintro2/functions/intro.md
- docs/courses/csintro2/functions/project.md
- docs/courses/csintro2/logic/booleans.md
- docs/courses/csintro2/logic/intro.md
- docs/courses/csintro2/logic/multiplayer.md
- docs/courses/csintro2/logic/project.md
- docs/courses/csintro2/logic/while.md
- docs/courses/csintro2/review/side-scroller.md
- docs/courses/csintro2/tilemap/intro.md
- docs/courses/csintro2/tilemap/project.md
- docs/examples/dodge-rock.md
- docs/examples/level-game.md
- docs/examples/space-destroyer.md
- docs/lessons/cherry-pickr.md
- docs/tutorials/simple-maze.md
- libs/device/startup.ts
- package.json
- pxtarget.json
Should be everything, somehow my local serve got messed up a bit ago though so I have to fix that to sanity check everything
(the pxtarget.json change probably needs a sanity check, stole the format from adafruit upgrades)
> controlSprite->moveSprite: Upgrade path and docs fixes

- package.json
- pxtarget.json
Bumping to latest pxt-core and enabling script manager.
> Enable script manager

- docs/examples/eater-princess.md
Updating with new API and assets.
> Updating eater princess with new API

- libs/base/shims.d.ts
- libs/buttons/shims.d.ts
- libs/controller---hw/targetoverrides.ts
- libs/core---samd51/dal.d.ts
- libs/core---stm32f103/dal.d.ts
- libs/core---stm32f401re/dal.d.ts
- libs/core/dal.d.ts
- libs/jacdac/shims.d.ts
- package.json
- pxtarget.json
Grabbind the JACDAC with debug support
> updating jacdac debug branch

- libs/hw---samd51/pxt.json
- libs/hw---stm32f103/pxt.json
- libs/hw---stm32f401/config.ts
- libs/hw---stm32f401/pxt.json
> Update pin definition for jacdac

- libs/jacdac/shims.d.ts
- package.json
- pxtarget.json
> pick up JACDAC memory fix

- docs/courses/csintro1/intro/birthday-algorithm.md
- docs/courses/csintro1/intro/info.md
- docs/courses/csintro1/intro/makecode-orientation.md
- docs/courses/csintro1/intro/sprites.md
- docs/courses/csintro1/intro/variable-math.md
- docs/courses/csintro1/loops/increment-loop.md
- docs/courses/csintro1/motion/create-on-create-sprites.md
- docs/courses/csintro1/motion/overlap1.md
- docs/courses/csintro1/motion/sprite-motion-event.md
- docs/courses/csintro1/sprites/collage.md
- docs/courses/csintro1/sprites/coordinate-walker.md
- docs/courses/csintro1/sprites/hello-sprite.md
- docs/lessons/cherry-pickr.md
- docs/tutorials/happy-flower.md
- docs/tutorials/simple-maze.md
- docs/tutorials/star-field.md
- libs/blocksprj/main.blocks
Don't include on game update by default as it's a bit advanced
> Remove on game update and adjust docs

- package.json
- sim/controlPad.ts
> don't trigger menu too easily

- libs/device/startup.ts
Requires https://github.com/Microsoft/pxt-common-packages/pull/534
> inject volume items in menu

- pxtarget.json
Fix for https://github.com/Microsoft/pxt-arcade/issues/394
> move debugger to experiments

- docs/examples/space-destroyer.md
pick random block was removed by https://github.com/Microsoft/pxt-common-packages/pull/561
> Remove Math.pickRandom from tutorial

- docs/courses/csintro1/motion/create-on-create-sprites.md
- docs/courses/csintro1/project/example.md
- docs/courses/csintro1/review/paparazzi.md
- docs/courses/csintro2/logic/multiplayer.md
required to update common packages after https://github.com/Microsoft/pxt-common-packages/pull/563
> remove empty sprite from courses

- docs/courses/csintro1/about/authors.md
- docs/courses/csintro1/about/script.md
- docs/courses/csintro1/intro/birthday-algorithm.md
- docs/courses/csintro1/intro/info.md
- docs/courses/csintro1/intro/makecode-orientation.md
- docs/courses/csintro1/intro/unplugged.md
- docs/courses/csintro1/intro/variable-math.md
- docs/courses/csintro1/sprites/characters.md
- docs/courses/csintro1/sprites/coordinate-walker.md
- docs/courses/csintro1/sprites/unplugged.md
A set of simple edits to the first part of CSIntro Uint 1.
> CSIntro1 chunk 01 edits

- docs/courses/csintro1/loops/physics.md
- docs/courses/csintro1/loops/projectile-from.md
- docs/courses/csintro1/loops/projectiles.md
- docs/courses/csintro1/review/dodgey-duck.md
update to new apis in csintro1
> CS Intro 1 Projectiles updates

- package.json
Adding dedicated controller client
> bump jacdaccontroller

- docs/examples/duck.md
> Duck changing back to Any button

- pxtarget.json
needed after https://github.com/Microsoft/pxt-common-packages/pull/620
> remove particles as separate extension

- docs/tutorials/eat-the-doughnut.md
A few edits for 'Eat the Doughnut'.
RE: #540
> Edits for the 'doughnut' tutorial

- package.json
- pxtarget.json
- sim/simulator.ts
Requires https://github.com/Microsoft/pxt/pull/5163
> PNG Phoenix

- docs/hardware.md
Cards get loaded in the hardware page.
> dummy hardware page

- libs/screen---st7735/targetoverrides.ts
> Simulator crash fix

- package.json
- pxtarget.json
- sim/simulator.ts
Support for 
Requires https://github.com/Microsoft/pxt/pull/5182
> Support for simulator screenshots in share dialog

- docs/developer.md
- docs/developer/button-tester.md
Add more note info to button tester and a link to it.
> Add button tester note and link

- sim/public/sim.css
- sim/public/simulator.html
- sim/simulator.ts
Use with https://github.com/Microsoft/pxt/pull/5192
> don't show square while loading

- docs/lessons/barrel-dodger.md
fix a few issues in the lesson that caused barrels not to spawn properly and the game to be too hard
requires https://github.com/Microsoft/pxt-common-packages/pull/641 for proper positioning
closes #478
> Barrel dodger lesson clean up

- docs/courses/csintro1/sprites/unplugged.md
* removed Bing link for Sink a Ship unplugged lesson
> Removed Bing link for Sink a Ship unplugged lesson

- package.json
- pxtarget.json
- sim/api.ts
- sim/simulator.ts
P keyboard shortcut Requires https://github.com/Microsoft/pxt/pull/5196
> Screenshot key

- docs/examples/catch.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/pxt-arcade/631)
> Adjust player move speed to make it a little less jumpy

- docs/tutorials/simple-maze.md
> fix empty sprite kinds in simple maze

- pxtarget.json
upgrade rules to handle as much as possible with just regex switches
> upgrade rules

- docs/tutorials/eat-the-doughnut.md
> Help the donut part 2

- docs/tutorials/lemon-leak.md
Use ``SpriteKind.Projectile`` for strawberry attackers.
RE: #677
> Change projectile kind in Lemon Leak

- sim/controlPad.ts
- sim/public/sim.css
- sim/simulator.ts
Support for multi-touch in simulator.
Test - https://arcade.makecode.com/developer/button-tester
> Multitouch support in simulator.

- docs/hardware.md
- docs/projects.md
- targetconfig.json
Add "hardware" cards on the home page + "Add Custom Board" card as well.
> Hardware in home

- docs/SUMMARY.md
- docs/reference.md
- docs/reference/music.md
> Add in the 'music' card page

- package.json
Addresses https://github.com/Microsoft/pxt-arcade/issues/698
> Move sim to optional dependencies

- package.json
> sim v0.6.1

- libs/core---samd/shims.d.ts
- libs/core---stm32/shims.d.ts
- libs/core/shims.d.ts
- package.json
Moving most of SPI/I2C/Serial to typescript.
> I2c device refactoring

- libs/core---samd/shims.d.ts
- libs/core---stm32/shims.d.ts
- libs/core/shims.d.ts
- package.json
Updated shims from https://github.com/Microsoft/pxt-common-packages/pull/693
> Updated shims for light refactoring

- pxtarget.json
Fixes https://github.com/Microsoft/pxt-arcade/issues/734
> Fix sprite icon in function editor

- editor/extension.ts
Adding an upgrade rule for this PR: https://github.com/Microsoft/pxt-common-packages/pull/712
> Adding upgrade rule for gamesettile

- docs/courses/.crowdinignore
Remove crowdin file to skip folder.
> upload courses to crowdin

- pxtarget.json
> enable chinese simplified in language picker

- libs/accelerometer/pxt.json
- libs/buttons/pxt.json
Those packages should not be added directly.
Requires https://github.com/Microsoft/pxt/pull/5351
> hide buttons, accelerometer

- .github/PULL_REQUEST_TEMPLATE/game_submission.md
- docs/community/blocks-template.md
- docs/community/javascript-template.md
- docs/submitting-games.md
For users to submit their own games
> First draft of game submission instructions

- .github/pull_request_template.md
- docs/game-submission.md
> updated submission process

- package.json
- pxtarget.json
Automatically patches project with "serial" or "edge-connector" packages.
Requires https://github.com/Microsoft/pxt/pull/5380
> added patching

- package.json
> bump pxt 5.6.2

- theme/theme.config
Seems that the theme.json from the pxt-sample is quite outdated and we are probably loosing some PXT stylig in arcade. or is it by design?
> aligning theme for pxt

- theme/style.less
> Fixing corner radius of sim play button overlay

- theme/theme.config
Fixing the theme did more damaged than expected. Reverting until we can investigate more.
> revert theme changes

- package.json
- pxtarget.json
> Remove python and refer pxt-core to 5.6.4

- package.json
> Updating to latest pxt 5.6 stable and latest common packages

- pxtarget.json
@Jaqster wants to keep autorun enabled for this release. We are going to test on Monday and see if the perf issues are worse than what we have today.
> Enable autorun of simulator

- package.json
> bump pxt python

- docs/tutorials/chase-the-pizza.md
Clarify that ``mySprite2`` is the next set sprite block to pull out.
Fixes #850 
@ChaseMor
> 'Chase the Pizza' step 5 fix

- docs/about.md
- docs/hardware/adding.md
- package.json
> adding chapter sections

- package.json
- pxtarget.json
Enables QR code generation. Harmless if pxt not updated yet. https://github.com/Microsoft/pxt/pull/5454
> enable qrcode generation

- docs/tutorials.md
Typo in tutorial card description.
> Typo in 'Galga' card description

- docs/examples/seven-segment.md
- libs/sevenseg/sevenseg.ts
Add a getter for the counter.
Should we also change ``setCounterValue(value: number):`` to just be a setter for the property?
> Slim down seven-segment APIs

- docs/tutorials/chase-the-pizza.md
- docs/tutorials/galga.md
- docs/tutorials/happy-flower.md
- docs/tutorials/lemon-leak.md
- docs/tutorials/simple-maze.md
Prepends tutorial paths with a slash.
Fixes Microsoft/pxt-arcade#889
> Fixed tutorial direct links

- docs/offline-app.html
Serving offline-app-template file. Requires https://github.com/Microsoft/pxt/pull/5496 to be merged.
> adding offline app template

- docs/examples/jumpy-platformer.md
that richard found with his monaco debugger
> Fix jumpy platformer useless animation bug

- docs/examples/seven-segment.md
> Sevenseg example temperature meter

- libs/base/basic.ts
- package.json
Fixes #920 
Probably want to merge about the same time as bumping to include https://github.com/Microsoft/pxt-common-packages/pull/799 to avoid having both blocks at once
> Move forever back to loops

- docs/hardware/errors.md
Quick start on a page to direct people for friendlier descriptions / examples of errors that can show up on hardware / what they mean. I only did the handful that I've actually seen occur / seem like potentially common errors to start with.
Also have no idea where to link this, so left it as a page; any suggestions? Just in the summary and hope they find it if they search?
(And also just wrote it up without editting, so I'll spend an extra minute before merging checking for typos / poor phrasing)
> Quick start for a 'common errors on hw' page

- docs/examples/paint-brush.md
Just missed getting this edit in #937.
> 'Brush up' the description for Paint Brush example

- docs/hardware/errors.md
A few edits to the HW errors page.
RE: #930
> Edits on the hardware errors page

- docs/courses/csintro2/arrays/intro.md
- docs/courses/csintro2/arrays/sprites.md
- docs/courses/csintro2/arrays/string.md
- docs/courses/csintro2/arrays/tilemap.md
- docs/courses/csintro2/logic/booleans.md
- docs/courses/csintro2/logic/intro.md
- docs/courses/csintro2/logic/multiplayer.md
- docs/courses/csintro2/logic/user-input.md
- docs/courses/csintro2/logic/while.md
- docs/courses/csintro2/tilemap/extensions.md
Edited csintro2 video links as requested by @eric-camplin
> Edited csintro2 video links

- docs/courses/csintro1/about/teachers.md
- docs/courses/csintro2/about/teachers.md
- docs/courses/csintro3/about/teachers.md
Update edits for @eric-camplin 's teacher materials page.
Closes #973
> Update csintro1 teacher materials page

- libs/thermometer/enums.d.ts
- libs/thermometer/pxt.json
- libs/thermometer/shims.d.ts
- package.json
- pxtarget.json
Support for tempature in controller.
Requires https://github.com/microsoft/pxt-arcade-sim/pull/8 https://github.com/microsoft/pxt-common-packages/pull/840
> adding thermometer

- pxtarget.json
> bump codal with neopixel fix

- libs/hw---rpi/keys.cpp
also optimize key reading a bit
> Allow for second player on RPi0

- docs/developer/sound.md
Updates the documentation to include information about ramping the frequency of tones.
> Updated sound docs to include frequency ramping

- libs/hw---vm/sdlmain.cpp
> URL activation and vm image caching support

- docs/javascript-games.md
- docs/javascript-games/ping.md
Small additions to the ping game text. Sorry, I missed catching the original PR.
RE: #1044
> Ping review edits

- docs/john-parks-workshop.md
Mess with the card descriptions and fix the timestamps on the youtube links.
RE: #1041
> John Park Gallery edits

- docs/courses/csintro3/arrays/strings-problems.md
Fixed line where sample code was incorrectly calling a sample function
> Fixed course problem set so that sample code compiles

- docs/hardware/raspberry-pi/cardboard-control-panel/assemble.md
- docs/hardware/raspberry-pi/cardboard-control-panel/rpi-setup.md
Add a few edits to the RPI panel config update.
RE: #1059
> A few edits to the rpi panel update

- docs/concepts/setting-the-scene.md
- docs/lessons/barrel-dodger.md
- docs/tutorials/simple-extensions.md
- docs/tutorials/simple-maze.md
Change tutorials, etc. with discussion about wall setting to match the newer ``set tile`` block.
Closes #1077
> Adjust text to match newer tile wall setting

- libs/core---linux/shims.d.ts
- libs/core---samd/shims.d.ts
- libs/core---stm32/shims.d.ts
- libs/core---vm/shims.d.ts
- libs/core/shims.d.ts
- package.json
Requires https://github.com/microsoft/pxt-common-packages/pull/870
> Don't sleep on USB

- pxtarget.json
Use with microsoft/pxt/pull/5687
> Add 'ie' to unsupported browsers for arcade

- docs/john-parks-workshop.md
@ChaseMor noticed these were broken: https://youtu.be/mZeyxi75Kyo&t=405s, looks like the & doesn't work
> fix home page links to john park youtube videos; s/&/?/

- docs/blocks-games/jumpy-platformer.md
- docs/javascript-games/ping.md
Minor clean up on jumpy platformer and ping, (convert to use namespace sprite kinds, and remove some weird behavior from both that was added to make it work with the old live site)
> clean up jumpy platformer and ping

- docs/SUMMARY.md
- docs/lessons.md
Linkup Dance Party lesson.
This PR is for changes from #1123
> Dance Party lesson linkup

- docs/courses/csintro3/intro/math.md
> Correct error in csintro3 math

- libs/hw---rpi/gamesel.cpp
- libs/hw---rpi/shims.d.ts
> delete program support

- docs/courses/csintro1/loops/projectile-from.md
- docs/courses/csintro1/loops/projectiles.md
- docs/courses/csintro1/review/dodgey-duck.md
- docs/courses/csintro3/arrays/images.md
- docs/courses/csintro4/data/operations.md
- docs/courses/csintro4/project-guidelines.md
- docs/tutorials/lander.md
- pxtarget.json
checkdocs errors on travis haven't been blocking travis since june. The build is fixed with all the conversions from enums -> consts, so the flag can be removed and travis can show errors again now! 🎉🎉
also fixes a few checkdocs errors that got missed, and a handful of other (harmless) whitespace issues that II must have forgotten to save in the last change.
> fix checkdocs again, fail travis build on failure, and whitespace fixes

- docs/graphics-math.md
- docs/graphics-math/animated-sand.md
A few lines of additional description.
Y-axis tilt is seems inversed in the sim.
> Add extra descripto to AniSand

- package.json
Includes Joey's Renderable changes
> bump common-packages version

- docs/tutorials/galga.md
Initial commit fixes #1187, but I feel like there still are issues with this tutorial.
- According to the game's description, "You can take only three hits." However, every time you shoot an enemy, you gain a life. Is that correct, or should the score be changing instead?
- ~~When the player's ship collides with an enemy, it never respawns. You can keep shooting ... but the darts appear out of thin air. Is that supposed to be an exercise left to the student? If so ... shouldn't we say that at the end?~~
@ganicke, I know you are the original author, and @pelikhan is the initial reviewer, so I'll tag you two. 😄 Others, of course, are more than welcome to comment as well. I'll mark this as a draft for now until I hear back with thoughts on these two items (and any others).
> Galga tutorial corrections

- docs/developer.md
- docs/developer/game-loop.md
- docs/javascript-games/caterpillar.md
- docs/javascript-games/darker-duck.md
- docs/javascript-games/ping.md
Add docs describing the current game loop; since the rendering loop would change with https://github.com/microsoft/pxt-common-packages/pull/917 I just described that one for now, so marking as a draft until that goes in or I update this to reflect whatever the final game loop ends up being
> Add docs describing game loop / physics / rendering

- docfiles/script.html
For testing this PR: https://github.com/microsoft/pxt-backend/pull/185
> add a comment to test our new doc versioning system

- libs/base/shims.d.ts
- package.json
- pxtarget.json
Should fix https://github.com/microsoft/pxt-arcade/issues/1216
> Update pxt-common-pkgs and stm32 codal

- docs/tutorials/simple-maze.md
> Remove unnecessary action from Simple Maze tutorial

- pxtarget.json
Enable share on tutorial finished. https://github.com/microsoft/pxt/pull/5865
> enable share on finished tutorial

- pxtarget.json
> Duplicate twitter handle in the tweet

- pxtarget.json
Uses https://github.com/microsoft/pxt/pull/5866 but won't break anything
> Enable nameProjectFirst

- package.json
- pxtarget.json
> Auto run is back

- libs/d5prj/pxt.json
- libs/f4prj/pxt.json
- libs/rpiprj/pxt.json
- pxtarget.json
Prebuilt native images for F5, D5, RPI so that it gets added to the app manifest and available offline.
> Prebuild hw projects

- package.json
> Bump pxt-arcade-sim

- pxtarget.json
> enable gif recoring

- docs/hardware/raspberry-pi/cardboard-control-panel/rpi-setup.md
Docs info from Stu Lowe's VGA investigation.
> VGA specific setup

- docs/tutorials/chase-the-pizza.md
There's only one use of 'start countdown' so don't say "put in another".
Closes #1329
> Chase pizza 'start coundown' wording

- docs/lessons/block-out.md
fixes https://github.com/microsoft/pxt-arcade/issues/1326
> Fix typo in blockout link

- docs/hardware/adding.md
added link to new reference design repo and removed outdated schematic snippets
> updated in light of new reference design repo

- docfiles/script.html
for the purpose of testing docs versioning.
> meaningless change to doc file

- package.json
This includes the meaningless docs changes so we can test docs versioning
> Bump pxt version

- docs/projects.md
- package.json
> bump pxt 5.24.13

- docs/concepts/star-field.md
Fix block text naming and some other edits.
Closes #1395
> Dusting edits for 'starfield'

- docs/developer/game-loop.md
> fix typo ender

- docs/physics-tests.md
- docs/physics-tests/bouncing-burger.md
- docs/physics-tests/double-collisions.md
- docs/physics-tests/explicit-positioning.md
- docs/physics-tests/from-player.md
- docs/physics-tests/shapes.md
- docs/physics-tests/single-collisions.md
- docs/physics-tests/space-man.md
- docs/physics-tests/spooky-treats.md
- docs/physics-tests/tiles.md
- docs/physics-tests/wall-jump.md
Add some edits to the "Physics tests" pages.
RE: #1404
> Edits to the 'physics test' doc set

- README.md
- docs/contact.md
- docs/developer.md
- docs/developer/sound.md
- docs/hardware/adding.md
- docs/touchdevelop.md
- package.json
- pxtarget.json
Microsoft org in github is lowercased.
> Microsoft -> microsoft

- theme/theme.config
@pelikhan this is why the login bubble is so big in https://github.com/microsoft/pxt/pull/6114's build
> use same overrides as microbit

- pxtarget.json
Required for https://github.com/microsoft/pxt/pull/6163
I think this was just copy/pasted from pxt-sample or something. It should be device.
> Fixing corepkg

- libs/device/pxtsnippets.json
Requires https://github.com/microsoft/pxt/pull/6231
> use variableName feild in snippet builder

- package.json
- pxtarget.json
Use OAuth authentication flow instead of developer token.
> Enable OAuth authentication flow for GitHub

- docs/hardware/raspberry-pi/cardboard-control-panel/rpi-setup.md
I've updated .zip files in the Adafruit guide, so this one can be simplified.
> Simplify RPi setup instructions

- docs/nfl.html
- docs/tutorials/football.md
move to use microsoft/pxt-kickoff re: https://github.com/microsoft/pxt-arcade/pull/1496#issuecomment-558857056
> move pxt-kickoff to microsoft org

- libs/buttons/shims.d.ts
- libs/core---linux/shims.d.ts
- libs/game---hw/controlleroverrides.ts
- libs/hw---rpi/keys.cpp
- package.json
Support for https://github.com/microsoft/pxt-common-packages/pull/934
> Add pressureLevel() to keys/RPi

- libs/core---samd/shims.d.ts
- libs/core---stm32/shims.d.ts
- libs/core---vm/shims.d.ts
- libs/core/shims.d.ts
- libs/game---hw/pxt.json
Refresh a few shims and mark game---hw as partial. Use with https://github.com/microsoft/pxt/pull/6275
> fix warnings

- docs/contact.md
- docs/tutorials/happy-flower.md
- docs/tutorials/lander.md
- docs/tutorials/simple-extensions.md
Fix some typos found by translators in Crowdin:
* https://crowdin.com/translate/kindscript/5826/en-fr#402694
* https://crowdin.com/translate/kindscript/3803/en-fr#230791
* https://crowdin.com/translate/kindscript/3803/en-fr#229305
* https://crowdin.com/translate/kindscript/6924/en-fr#612760
* https://crowdin.com/translate/kindscript/6924/en-fr#612750
* https://crowdin.com/translate/kindscript/3801/en-fr#511652
* https://crowdin.com/translate/kindscript/3801/en-fr#511638
> Fix typos found thru Crowdin - 12052019

- package.json
> bump common packages

- pxtarget.json
- theme/site/globals/site.variables
- theme/style.less
> New arcade theme colors

- theme/style.less
CSS styling for https://github.com/microsoft/pxt/pull/6336
> CSS for hardware button, white play button

- package.json
Fixes: https://github.com/microsoft/pxt-arcade/issues/1570
> bump arcade sim to new teal version

- pxtarget.json
close https://github.com/microsoft/pxt-arcade/issues/1601
> make snippet builder an experiment again

- libs/base/shims.d.ts
- theme/site/globals/site.variables
- theme/style.less
> Swapping button colors and tweaking menu to meet color contrast

- theme/site/globals/site.variables
Requires https://github.com/microsoft/pxt/pull/6389
> Set tutorial prev/next button color

- pxtarget.json
Requires https://github.com/microsoft/pxt/pull/6403
> Enable keymap for arcade simulator

- docs/nfl.html
- docs/tutorials/football.md
also needs https://github.com/microsoft/pxt-common-packages/pull/1054, as it just crashes immediately otherwise due to starting with the __palette buffer
> fix nfl game

- package.json
> update to pxt 5.31.8, 6.18.2

- targetconfig.json
> remove cards following update

- package.json
> bump sim to 0.7.6

- libs/template/index.html
- package.json
Slimmer simulator runner temp0late.
> slim simulators

- package.json
> bump sim reference to 0.7.7

- package.json
> bump to sim 0.7.9

- docs/nfl.html
> use pre-compiled game in nfl page

- docs/publishing-games.md
- libs/template/index.html
re: bad initial embed view on https://github.com/microsoft/pxt-arcade/pull/1716; might as well allow query params so people can have good sites and embed :)
https://jwunderl.github.io/test/
https://jwunderl.github.io/test/?embed=1
https://jwunderl.github.io/test/?nofooter=1
https://jwunderl.github.io/test/?embed=1&nofooter=1
> add params for nofooter / embed (no background)

- docs/nfl.html
- docs/publishing-games.md
Use nfl game as example re: https://github.com/pelikhan/falling-duck/pull/1#issuecomment-577525668; I added the query params to the /nfl page as well, will get the repo back up to date w/ the standard index.html after this is in~
> use nfl game as example for instead of falling duck

- libs/template/.github/workflows/makecode-release.yml
- libs/template/assets/js/loader.js
- libs/template/pxt.json
- package.json
Update template. Requires https://github.com/microsoft/pxt/pull/6504
> Updated template to point to release with binaries

- docs/tutorials.md
hide lander, it doesn't really work well with the new tilemap
> hide lander

- libs/template/assets/js/loader.js
- package.json
Use meta information to open correct download file
Requires https://github.com/microsoft/pxt/pull/6507
> fix loader to point to correct build location

- theme/site/globals/site.variables
> Increase opacity of toolbox, don't fade toolbox text

- libs/template/.github/workflows/makecode-release.yml
- libs/template/assets/js/loader.js
> Simplify release workflow

- targetconfig.json
Can be merged and will eventually shuffle scripts.
> shuffle community scripts

- targetconfig.json
Released version of arcade does not support this format.
> fix carousel link

- package.json
Picking up collapsible tutorial fix.
> Patch v0.15 with pxt v5.30.43

- docs/tutorials/galga.md
Rewriting instructions to describe the instruction to do. Also break out some steps.
> Galga simple

- docs/tutorials/galga.md
A few edits for Galga with the new ToDo descriptions.
RE: #1804
> Some edits to 'Galga' with the new ToDo style

- docfiles/script.html
- pxtarget.json
weird https://makecode.com/org link
> fix makecode url

- README.md
This came up during onboarding. It's important to know how to run gulp to make changes.
> Update Arcade README.md to mention gulp

- pxtarget.json
depends on: https://github.com/microsoft/pxt/pull/6852
> Enable ErrorList experiment option

- libs/template/assets/js/loader.js
see https://github.com/microsoft/pxt/pull/6886
> setstate change

- docs/lessons.md
- docs/tutorials.md
- docs/tutorials/barrel-dodger.md
Updated tutorials for digital all stars
> moving barrel dadger to tutorials

- docs/tutorials/barrel-dodger.md
The steps make more sense in this order.
> reorg steps in barrel dodger

- libs/keyboard/shims.d.ts
- package.json
> Keyboard cleanup

- docs/advanced-stream.md
- docs/tutorials/paddle.md
Some edits for the **Paddle** tutorial.
RE: #1881
> Paddle edits

- docs/static/gamejam/rules.md
Change Heist theme to Gardening in Game Jam rules.
> Garden jam writeup

- docs/gamejam.html
- docs/static/gamejam/gamejam.css
- docs/static/gamejam/gamejam.js
- docs/static/gamejam/gamejam.ts
Requires https://github.com/microsoft/pxt/pull/7147
\+ small CSS change for "Watch on mixer" button
> Add telemetry to game jam page

- package.json
Allows JACDAC messages to be imported separately
> support for sim messages

- docs/courses/csintro1/motion.md
- docs/courses/csintro1/motion/create-on-create-sprites.md
- docs/courses/csintro1/motion/overlap1.md
- docs/courses/csintro1/motion/overlap2.md
- docs/courses/csintro1/motion/project.md
- docs/courses/csintro1/motion/random.md
- docs/courses/csintro1/motion/sprite-motion-event.md
Updates to the Motion section for the CSIntro 1 review project.
> CSIntro1 Updates - Motion section

- docs/courses/csintro1/sprites/characters.md
- docs/courses/csintro1/sprites/collage.md
- docs/courses/csintro1/sprites/coordinate-walker.md
- docs/courses/csintro1/sprites/hello-sprite.md
Updates to the Sprites section for the CSIntro 1 review project.
> CSIntro1 Updates - sprites section

- docs/courses/csintro1/project/example.md
- docs/courses/csintro1/project/final.md
Updates to the Project section for the CSIntro 1 review project.
> CSIntro1 Updates - Project section

- docs/courses/csintro1/review.md
- docs/courses/csintro1/review/asteroid-blaster.md
- docs/courses/csintro1/review/baseball-catching.md
- docs/courses/csintro1/review/dodgey-duck.md
- docs/courses/csintro1/review/paparazzi.md
Updates to the Review section for the CSIntro 1 review project.
> CSIntro1 Updates - Review section

- docs/static/gamejam/rules.md
For https://github.com/microsoft/pxt-arcade/issues/1970
- Add link to "Collect the Clovers" tutorial
- Move gardening tips up
> Game jam page: link clover tutorials, move tips section

- docs/tutorials/collect-the-clovers.md
Include a couple of edits suggested in #2020 and a few others too.
Closes #2020
> Suggested edits for 'Collect the Clovers'

- pxtarget.json
Depends on: microsoft/pxt#7235
> Enable Blocks ErrorList experiment

- docs/static/gamejam/gamejam.css
- docs/static/gamejam/gamejam.js
- docs/static/gamejam/gamejam.ts
> Populate game jam gallery with submitted games

- targetconfig.json
> add pxt status bar extension

- docs/concepts/throw-a-bone.md
fix https://github.com/microsoft/pxt-arcade/issues/2081, clarify it's an 'after tutorial is finished' sorta suggestion / fill out with more interesting challenges~
> fix wording on throw a bone tutorial

- docs/javascript-games/darker-duck.md
fix https://github.com/microsoft/pxt-arcade/issues/2119
> fix darker duck example now that x / y are floats

- docs/courses/csintro1/intro/sprites.md
- docs/courses/csintro1/loops/projectile-from.md
- docs/courses/csintro1/loops/projectiles.md
- docs/courses/csintro1/motion/create-on-create-sprites.md
- docs/courses/csintro1/motion/overlap1.md
- docs/courses/csintro1/sprites/collage.md
Replace links for outdated CSIntro1 videos with the updated video links:
* Unit 1 Introduction: Sprites - Concept set a sprite variable to an image using image editor  https://youtu.be/gCtzHzg_BZM
* Unit 2 Sprites: Sprite Collage - Example 1 sprite and background  https://youtu.be/_0q2tEsrdbM
* Unit 3 Motion: On Created - Concept create with on created event  https://youtu.be/XR8DmTOdgNc
* Unit 3 Motion: Overlap Section 1 - Concept overlap event  https://youtu.be/TSUsPc0Kuo8
* Unit 4 Loops: Projectiles - Concept flying birds  https://youtu.be/1CWWoSy0Tso
* Unit 4 Loops: Projectiles from Sprites - Concept projectile from sprite  https://youtu.be/bX9FOLNmScA
> Change links for updated CSIntro1 videos

- docs/advanced-stream.md
It results in an error due to duplicate key
> remove duplicate stream from list

- docs/static/gamejam/gamejam.js
- docs/static/gamejam/gamejam.ts
- docs/static/gamejam/rules.md
fixes https://github.com/microsoft/pxt-arcade/issues/2210
Updated Snail Hike: https://arcade.makecode.com/27830-69912-67539-85378
Whenever the snails climb, in addition to turning gravity off, I'm changing vy to be 0 too (which was the intended effect of changing gravity to 0).
> Update Snail Hike to work with beta

- pxtarget.json
just checked and it appears almost entirely translated: https://arcade.makecode.com/?forcelang=ja
> add japanese to supported languages

- pxtarget.json
stable counterpart of https://github.com/microsoft/pxt-arcade/pull/2274 for released site
> [stable1.0] add japanese to selected language list

- docs/recipes/shark-splash/01-character.md
- docs/recipes/shark-splash/02-A-enemies.md
- docs/recipes/shark-splash/02-B-enemies.md
- docs/recipes/shark-splash/02-C-enemies.md
- docs/recipes/shark-splash/02-enemies.md
- docs/recipes/shark-splash/03-projectiles.md
- docs/recipes/shark-splash/04-background.md
Run some edits on the Shark Attack tutorials:
> Some edits for the Shark Attack tutorials

- package.json
fixes to show stats in sim again
> bump common packages to 8.1.6, sim to 0.7.20

- pxtarget.json
Also bump codal build system to 0.8.0
> Set flash sizes for various chips

- docs/offline-app.html
- pxtarget.json
couple changes re https://github.com/microsoft/pxt/pull/7398
> Offline app page updates

- docs/concepts/which-button.md
Correct the default button in step 6 to **A** where it previously was **any**.
Fixes #2360
> Correct default button for 'Which Button'

- docs/tutorials/happy-flower.md
Incorporate some of the edits suggested in #2116.
Closes #2116
> Do some suggested edits to 'Happy Flower'

- docs/gamejam-ref.json
- docs/gamejam/traffic.html
- docs/static/gamejam/jams/traffic/style.css
- Use regular redirect
- Office submission form 
- CSS tweak
> Small fixes for gamejam page

- targetconfig.json
pre merge TODO:
post merge TODO:
> Allowlist microsoft/pxt-tilemaps

- package.json
This includes new sounds waves.
cc @klausw
> Bump pxt-core to 6.3.15 and p-c-p to 8.2.4

- pxtarget.json
> enable french

- docs/recipes/side-scroller/01-background.md
- docs/recipes/side-scroller/02-create-car.md
- docs/recipes/side-scroller/03-control-car.md
Remove the options to go to the previous or last tutorial parts.
Closes #2457
> Remove before-last part options for 'Side Scroller'

- docs/static/gamejam/jams/traffic/info.json
- docs/static/gamejam/lib/gamejam.css
All entries + small CSS fix for long game names. Will do a separate PR with winners after announcement
> Final list of gamejam entries

- pxtarget.json
New configuration for supported identity providers.
> pxtarget.json changes for identity

- libs/storage/storage.cpp
Also make sure default files are present
> Make storage module compile without USB

- docs/hour-of-code.html
- docs/hour-of-code/educators.html
- docs/static/hour-of-code/styles.css
I missed the urls in style.css; they weren't getting resolved properly as they were using the cache url relative to style.less (which doesn't work as the path at the end of the relative url is just for pretty printing / debugging - it was trying to load style.less as a png)
Also added back the home tick, as I noticed there was a home button (the id just wasn't set)
> Fix hour of code page background images and add home tick

- docs/static/gamejam/lib/gamejam.css
> Small CSS updates for gamejam page image sizing

- docs/hour-of-code.html
Change the document open for activities and a few other things:
RE: #2520
> A few activity button changes for HOC landing page

- docs/recipes/shark-splash/00-map.md
putting up an example file so that we can test maps hosted from our docs as well
> Add map markdown for Shark Splash

- libs/template/assets/index.html
- libs/template/assets/js/custom.js
- libs/template/assets/js/loader.js
- libs/template/index.html
- libs/template/pxt.json
This change makes it easier for advanced users to customize the generated github pages web site sources.
> GitHub Pages: support for custom javascript

- docs/hardware/raspberry-pi/wooden-cabinet.md
Run a few edits on the wooden cabinet page. Decided that bullet items here are mostly full sentences rather than just fragments.
RE: #2561
> Wood Arcade cabinet edits

- docs/hour-of-code.html
There is not much users do in the online editors. Point to the minecraft setup.
> Point to the Minecraft setup instead of live website

- docs/static/hour-of-code/styles.css
A few mobile adjustments to the HOC page.
> Hour of code mobile

- docfiles/script.html
- targetconfig.json
port https://github.com/microsoft/pxt-arcade/pull/2575 for release. I bumped the stable common packages / pxt versions already so this should be the last thing to prep the release: https://github.com/microsoft/pxt-arcade/commit/4a2fbc8bd8f220be6097fed579479f792f771090
> [stable1.2] simulator tick events

- docs/courses/csintro1/intro/birthday-algorithm.md
- docs/courses/csintro1/intro/info.md
- docs/courses/csintro1/intro/makecode-orientation.md
- docs/courses/csintro1/intro/sprites.md
- docs/courses/csintro1/intro/variable-math.md
- docs/courses/csintro1/loops/increment-loop.md
- docs/courses/csintro1/loops/intro.md
- docs/courses/csintro1/loops/physics.md
- docs/courses/csintro1/loops/projectile-from.md
- docs/courses/csintro1/loops/projectiles.md
- docs/courses/csintro1/motion/overlap1.md
- docs/courses/csintro1/motion/overlap2.md
- docs/courses/csintro1/motion/random.md
- docs/courses/csintro1/motion/sprite-motion-event.md
- docs/courses/csintro1/sprites/collage.md
- docs/courses/csintro1/sprites/coordinate-walker.md
- docs/courses/csintro1/sprites/hello-sprite.md
Replacement video links for the unreachable aka links - CSIntro1.
> Replacement video links CSIntro1

- docs/ww84.html
Small changes to the wording to set expectations for the WW84 activity.
> Wording tweaks

- docs/game-jam.md
The "Traffic Jam" game contains so many blocks that the Workspace is super cluttered. @abchatra says remove the game from the list.
Closes #2623
> Unjam game jam from traffic jam

- docs/static/gamejam/jams/ocean/info.json
Have not had time to play/look through them, but these are all the entries we've gotten up til now
> Add ocean jam entries to landing page

- .travis.yml
- package.json
- targetconfig.json
> JACDAC + Hardware support

- docs/tutorials/simple-extensions.md
Convert the tilemaps in "Simple Extensions" to jres.
RE: https://github.com/microsoft/pxt-arcade/issues/2837#issuecomment-758471879
> Covert tilemaps in 'Simple Extensions' to jres

- docs/game-jam.md
Linkup an unjumbled version of the 'Split Cars'.
Fixes #2862
> Unjumbled gamejam 'Split Cars' project

- docs/concepts/setting-the-scene.md
fix https://github.com/microsoft/pxt-arcade/issues/2856 by switching it over to use jres snippet instead of inline tilemaps~
> fix setting the scene tutorial

- docs/reference/add-background-ref.md
Adding a placeholder to update later
> Placeholder reference doc for adding backgrounds

- docs/skillmap/story/card.md
- docs/skillmap/story/card2.md
Little edits to the md. I'll squash after the tests pass.
> Tiny final card polishes

- arcade.code-workspace
> remove workspace colors

- docs/lessons/cherry-pickr.md
Some fixes for block text and tilemap mentions.
Closes #2823 
Closes #2825
> A few 'Cherry Pickr' text fixes

- pxtarget.json
Just removing from the target flag
> Remove identity

- docfiles/script.html
- docs/static/script-page.css
This reverts commit 86e3616b43a071a12769aca253c3b89b00fda382.
a few of the links are messed up for some reason, causing 404s. Will fix that later
> Revert "Remove second iframe frame share page (#2753)"

- docs/skillmap/beginner-skillmap.md
Quick edits to md. I'll squash when tests succeed.
> Update beginner skillmap to get rid of error

- docs/skillmap/beginner-skillmap.md
I still can't get my beginner skillmap to pull up, so I removed "required" to narrow down issues.
> Kiki lee beginnermap update2

- docs/skillmap/beginner-skillmap.md
Shannon found the likely error. Uploading the fix.
> Removed pointer to clicker activity1

- docs/skillmap/beginner-skillmap.md
The activities on the other skillmap weren't opening, so I'm trying relative URLs.  Does this look right @shakao and @riknoll ?
> Updated skillmap to relative URLs

- docs/skillmap/beginner-skillmap.md
Simple URL add.  I'll squash when tests pass.
> fixed final URL on skillmap

- docs/skillmap/collector/collector2.md
> Finished collector2

- docs/gamejam/all.md
@ganicke something like this? feel free to edit haha
Closes #3012
> Move past gamejam directory to /gamejam/all, add hint

- .github/workflows/pxt-buildmain.yml
same as https://github.com/microsoft/pxt-arcade/pull/3055 but for stable branch; should fix bump to trigger release builds
> [stable1.3] Update pxt-buildmain.yml

- docs/skillmap/beginner-skillmap.md
One line added.  I'll squash when tests pass.
> added the next for collector4

- pxtarget.json
Reverts microsoft/pxt-arcade#2973
> Revert "Remove identity"

- docs/skillmap/interface/activity1.md
Small edit. I'll squash after tests pass.
> fixed urls

- docs/skillmap/beginner-skillmap.md
- docs/skillmap/educator-info/basic-map-info.md
- docs/skillmap/educator-info/int-map-info.md
- docs/skillmap/interface/activity1.md
- docs/skillmap/intermediate-skillmap.md
Added placeholder pages for teacher info.  I'll squash after they pass.
> Kiki lee updates3

- docs/skillmap/beginner-skillmap.md
- docs/skillmap/intermediate-skillmap.md
> Removed .md from teacher info inside skillmap files

- package.json
bump to pick up https://github.com/microsoft/pxt/pull/7884 and a bunch of other fixes
> Bump pxt-core to v6.9.11

- docs/skillmap/collector/collector1.md
- docs/skillmap/collector/collector2.md
- docs/skillmap/collector/collector3.md
- docs/skillmap/collector/collector4.md
> Updated collector photos and some other random tids.

- docs/publishing-games.md
Fixes a grammatical error in publishing-games.md
> Fix grammatical error

- docs/tutorials/spy/galga.md
> Kiki lee galgaspy creation

- pxtarget.json
Support for https://github.com/microsoft/pxt/pull/7906.
> enable allowparentcontroller

- docs/skillmap/beginner-skillmap-2.md
- docs/skillmap/platformer/activity4.md
- docs/skillmap/space/activity3.md
Fixes https://github.com/microsoft/pxt-arcade/issues/3190 and https://github.com/microsoft/pxt-arcade/issues/3183
#3183 #3190
I'll squash when tests pass.
> Fixes two bugs from Sheila

- pxtarget.json
- targetconfig.json
> updated jacdac sim defs

- targetconfig.json
A Turtle Logo implementation for Arcade
> Allowlist Mr-Coxall/turtle-logo

- targetconfig.json
> Change default skillmap to point at /docs

- docs/static/script-page.css
Port https://github.com/microsoft/pxt-arcade/pull/3343 for hotfix
> [stable1.4] Fix share page sizing on mobile safari (#3343)

- docfiles/script.html
cherry pick https://github.com/microsoft/pxt-arcade/pull/3351; likely not high priority because this has been broken on old edge for months without any complaints I've seen, but fix is minimal / probably good to include just in case.
> [stable1.4] Cherry pick edge share page fix

- docs/tutorials/galga.md
Just fixed a couple of hint blocks. Nothing scary.
I'll merge when tests finish.
> Fixed some galga issues

- package.json
to pick up https://github.com/microsoft/pxt/pull/8056
> [stable1.4] bump pxt-core to 6.12.15

- docs/skillmap/zoo.md
- docs/skillmap/zoo/zoo2.md
- docs/skillmap/zoo/zoo2a.md
- docs/skillmap/zoo/zoo3.md
- docs/skillmap/zoo/zoo4.md
- docs/skillmap/zoo/zoo5.md
Updated the rest of the Zookeeper files.  It should now feel like a cohesive experience where you can track what you've learned through all levels. 
I have yet to play it end to end with changes, I'll do that once this is merged.
Since this isn't in production, I'll go ahead and squash when tests pass.
> Zookeeper levels

- docs/gamejam/lessons/ocean.md
updating the URL with a game that has comments expanded, so users can see it
> Ocean starter game URL with expanded comments

- libs/hw---n3/config.ts
fixes https://github.com/microsoft/jacdac/issues/344
> Add jacdac pin to micro:bit config

- docs/skillmap/zoo/zoo1.md
- docs/skillmap/zoo/zoo2.md
- docs/skillmap/zoo/zoo2a.md
- docs/skillmap/zoo/zoo3.md
- docs/skillmap/zoo/zoo4.md
- docs/skillmap/zoo/zoo5.md
Went through and added categories back to the toolbox, then added the specifics to the instructions.  Low-risk. Will squash when tests pass.
> Added categories to Zookeeper

- package.json
Pick up https://github.com/microsoft/pxt-common-packages/pull/1253 for patch
> [stable1.4] bump pxt-common-packages to 8.8.4

- docs/static/gamejam/jams/time/rules.md
grumble grumble relative links grumble grumble
> Fix tutorial link

- docs/static/gamejam/jams/time/info.json
> Add initial submissions to game jam landing page gallery

- docs/tutorials/alien.md
> Fixed typo in Alien

- docs/skillmap/space/space1.md
- docs/skillmap/space/space2.md
- docs/skillmap/space/space3.md
- docs/skillmap/space/space4.md
Nothing big, I'll squash when tests pass.
> Fixed some typos

- docs/projects.md
- docs/tutorials.md
- targetconfig.json
> New skillmap card and aliases

- docs/static/gamejam/lib/gamejam.css
- docs/static/gamejam/lib/gamejam.d.ts
- docs/static/gamejam/lib/gamejam.js
- docs/static/gamejam/lib/gamejam.ts
we should now be able to automatically populate the honorable mentions div with all games that have descriptions. the top 3 places will still be manually added in the markdown because they have custom images, and more detailed reviews (with embedded links)
> Add description field to gamejam entries, pull honorable mentions from games with descriptions

- docs/skillmaps.md
- docs/tutorials.md
- targetconfig.json
Here are the changes I made to add a row for skillmaps…we'll see if tests pass!
I'll wait for approval before I push.
> Adding Skillmaps Row

- docs/skillmap/space.md
- docs/skillmap/space/space1.md
- docs/skillmap/space/space2.md
- docs/skillmap/space/space3.md
- docs/skillmap/space/space4.md
- docs/skillmap/space/space4a.md
- docs/skillmap/space/space5.md
- docs/skillmap/space/space6.md
Did some small changes based on user testing over the weekend.  I'll push when tests pass.
> Fixes for Space based on playthroughs

- docs/skillmap/shark.md
Changed the main .md doc to reflect the new level names, images, and descriptions.
> Change the skillmap to reflect the new levels

- docs/skillmap/shark.md
This reverts commit 4bae840f14192f27d4a9644d4823d26328b141f2.
> Revert "Update shark.md"

- docs/insiders.html
- docs/skillmap/clicker-themed/clickert2.md
- docs/skillmap/collector-themed/collectort2.md
- docs/skillmap/collector-themed/collectort3.md
- docs/skillmap/shark.md
- docs/skillmap/shark/shark1c.md
- docs/skillmap/shark/shark1d.md
- docs/skillmap/shark/shark4a.md
- docs/skillmap/zoo/zoo4.md
Shark, insiders, and some bug fixes
> Weeks edits

- docs/skillmap/shark.md
Connecting all the paths was doing something funky, so I dead-ended the optional paths.
I'll merge when tests pass.
> Shark map .md - dead-ended the optional paths

- docs/skillmap/shark.md
I added slashes before image and level urls…hopefully this fixes the frozen levels
I'll merge when tests pass
> Added leading slashes before level URLS

- docs/skillmap/jungle/jungle1.md
Missing bracket was keeping the level from functioning.
Uploading fix.
> Fixed two typos

- docs/skillmap/jungle/jungle1.md
- docs/skillmap/jungle/jungle2.md
Found another area that could have been causing problems…
> Fixed another set of inconsistencies

- package.json
Will merge once pxt 7.1.18 is done publishing
> bump pxt-core to 7.1.18

- docs/skillmap/educator-info/jungle-map-info.md
- docs/skillmap/educator-info/shark-map-info.md
- docs/skillmap/educator-info/space-map-info.md
*not all blocks currently render correctly
PR to put jungle learning outcomes file into master :)
Also made a few small nit changes to Shark and Space
> Angel jungle learning path

- docs/skillmap/sc.md
> Removed reference to "Mandarin"

- docs/skillmap/educator-info/jungle-map-info.md
- docs/skillmap/educator-info/sc-map-info.md
- docs/skillmap/sc/sc6b.md
Added a couple of tiny last-minute changes. I'll squash when tests pass.
> Updated teacher docs and the SC title

- docs/skillmap/educator-info/jungle-map-info.md
- docs/skillmap/sc.md
Two quick fixes, one requested by Marvel. I'll squash when tests pass.
> Tiny changes

- docs/skillmap/clicker-themed/clickert3.md
- docs/skillmap/sc.md
- docs/skillmap/sc/sc1.md
- docs/skillmap/sc/sc2.md
- docs/skillmap/sc/sc3.md
- docs/skillmap/sc/sc4.md
- docs/skillmap/sc/sc5.md
- docs/skillmap/sc/sc6.md
- docs/skillmap/sc/sc6a.md
- docs/skillmap/sc/sc6b.md
- docs/skillmap/sc/sc7.md
- docs/skillmap/sc/sc8.md
- Added helper rollover text for the SC custom blocks
- Removed typo in sc.md
- Fixed bug in clickert
Since SC now has so many eyes, I'd appreciate a review, @shakao  :)
> Added help hover text for SC blocks & debugged

- package.json
picks up https://github.com/microsoft/pxt/pull/8460, https://github.com/microsoft/pxt/pull/8458
> [stable1.5] bump pxt-core

- docs/skillmap/rockstar.md
- docs/skillmap/rockstar/rockstar1.md
- docs/skillmap/rockstar/rockstar2.md
- docs/skillmap/rockstar/rockstar3.md
- docs/skillmap/sc/sc3.md
- docs/skillmap/sc/sc4.md
- docs/skillmap/sc/sc5.md
- docs/skillmap/sc/sc6.md
- docs/skillmap/sc/sc6a.md
- docs/skillmap/sc/sc7.md
- Added :icons: to Rockstar
- Added end prompts to Rockstar
- Fixed some numbering in Shang-Chi
- Fixed 'nnamespace' in sc6a.md in hopes of fixing blanked out code
> Rockstar and Shang-Chi

- docs/skillmap/forest/forest1.md
Got the customts in the forest file.
Will merge when tests pass.
> Full Forest Fire

- package.json
https://github.com/microsoft/pxt/commit/f8929bfd9799ba111f83e3a80e192193481df947
> [stable1.5] Bumping pxt-core to 7.1.31

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
inspired by https://github.com/microsoft/pxt-arcade/pull/3034
to pick up these changes https://github.com/microsoft/pxt-arcade-sim/pull/50
> Bump pxt-arcade-sim to v0.8.6

- docs/skillmap/forest/forest3.md
- docs/skillmap/forest/forest4.md
- docs/skillmap/forest/forest9.md
Finished tutorial #3.  I didn't change anything anyone is using, so I'll squash when tests pass.
> Finished forest3.md

- docs/skillmap/forest/forest1.md
- docs/skillmap/forest/forest3.md
- docs/skillmap/forest/forest4.md
- docs/skillmap/forest/forest5.md
Almost done with level 4.  Need to figure out why the score isn't working.  I'll add that in next PR.
Will squash when tests pass.
> still building the forest

- README.md
- setup.cmd
- Minor modifications to README text
- Adds instructions for usage of setup.cmd on README
- Removes unreliable option from `setup.cmd`
> Adds instructions for using setup.cmd to README

- package.json
- theme/style.less
- theme/theme.config
Requires https://github.com/microsoft/pxt/pull/8506
> Upgrade the version of semantic-ui-less

- docs/skillmap/educator-info/forest-map-info.md
Updated the educator info page with last 2 game links.
(Still need to add final extension package).
> forest map teacher page

- docs/skillmap/shark/shark1-simple.md
- docs/skillmap/shark/shark2-simple.md
- docs/skillmap/shark/shark3-simple.md
- docs/skillmap/shark/shark4-simple.md
- docs/skillmap/shark/shark4a-simple.md
Last edits for the day :)
I'll merge when tests pass
> Final edits from my playthrough.

- docs/insiders.html
Added revised text to program overview
> Updated Insiders Page

- docs/beta-ref.json
This is to facilitate one week of testing.
> Pointing to beta to 1.7

- docs/gamejam/global-2021.html
- docs/static/gamejam/jams/global-2021/style.css
- docs/static/gamejam/lib/gamejam.css
- docs/static/hour-of-code/2021/styles.css
DO NOT MERGE until next monday
> Update Game Jam page

- docs/skillmaps.md
- targetconfig.json
Added Forest and Turkey
Also added a shortcut for the "star" map
Waiting for approval to push this afternoon.
> Updating skillmaps on homepage

- docs/skillmap/star.md
Still had a "clickert" reference in there
I'll squash when tests pass
> Updated Star map

- docs/skillmap/forest_new/forest1.md
- docs/skillmap/forest_new/forest2.md
- docs/skillmap/forest_new/forest3.md
- docs/skillmap/forest_new/forest4.md
- docs/skillmap/forest_new/forest5.md
- docs/skillmap/forest_new/forest6.md
- docs/skillmap/star/star2.md
Added newlines back into forest using  <br/>
Also fixed an issue in star2.md that Jacqueline found. 
I'll merge when tests pass.
> Added newlines back into forest

- docs/tutorials/winter.md
Merging fixes from Shakao's recommendations.  Will squash when tests pass.
> Polished Winter

- docs/hero-banner.md
Swapped link for HoC banner to the Game Jam page for final submission date…using the same image.
> Changed Hour of Code to Game Jam

- docs/gamejam/global-2021.html
Updated to show deadline has passed and highlight info that is still relevant.
I'll wait until @dmonroym  looks at it before I squash.
> Updated Global Game Jam Page

- docs/skillmap/racer.md
Small image change. I'll squash when tests pass.
> Changed default map gif

- docs/skillmap/racer.md
Updated racer.md
I'll squash when tests pass.
> Fixed remnants from old file

- docs/skillmap/racer/racer1.md
Made a couple of simple changes in racer1.md
> Fixed some wording in racer1

- docs/skillmap/racer.md
Fixed background error. Will squash when tests pass.
> Fixed typo in monster racer

- docs/skillmap/racer.md
- Made background a gif
- Fixed location of certificate preview
- Fixed name of certificate pdf
Will squash when tests pass
> Fixed 2 racer images

- docs/skillmap/racer/racer1.md
Updated some instructions.  I will merge when tests pass.
> Fixed level 1 based on feedback from design

- docs/hero-banner.md
Added the banner for Monster Racer.  I'll wait for someone to approve before squashing.
> Added Monster Racer banner

- docs/tutorials/valentine.md
Bringing some set-up code back to customts and updating extension.
Will squash when tests pass.
> Updated to bring some set-up back to ts

- docs/tutorials/valentine.md
Added comments to the existing game blocks (but they don't show by default)
Also updated to the new extension version
Will squash when tests pass.
> Updated extension and added comments

- docs/insiders.html
Updated page and previewed locally. 
Will merge once tests pass.
> Update Insiders page for Spring 2022

- docs/skillmap/star.md
Moved the badges to the end of the md and it fixed the issue.  Will merge when tests pass.
> Fixed issue with trophy on top of first level

- docs/tutorials/valentine.md
Changing the Valentine extension to the new and improved version.
Reviews for FYI only, I'll squash when tests pass.
> Add new extension to Valentine

- package.json
- pxtarget.json
& bump core version to pick up in context translation fix
> [stable1.8] change crowdin name kindscript -> makecode

- docs/skillmaps.md
The images should all pull from the same place as before, but I'll wait for approval to squash.
> Changed Sing 2 to Talent Show

- docs/skillmap/jungle/jungle1.md
- docs/skillmap/jungle/jungle2.md
- docs/skillmap/jungle/jungle3.md
- docs/skillmap/jungle/jungle4.md
- docs/skillmap/jungle/jungle5.md
- docs/skillmap/jungle/jungle6.md
- docs/skillmap/jungle/jungle7.md
- docs/skillmap/jungle/jungle8.md
- docs/skillmap/star/star4.md
- docs/tutorials/winter.md
Added updated simple-blocks extensions to files that used blocks that it contains.
Will squash when tests pass, but the changed skillmap will need a runthrough to make sure everything works as intended.
> Added simple block extension to tutorials

- docs/skillmap/beginner-skillmap.md
This is a widely used map, so I'll wait for approval.
I already tested privately.
> Unlocking beginner paths for Insiders

- libs/sevenseg/docs/reference/sevenseg/create-counter.md
- libs/sevenseg/docs/reference/sevenseg/create-digit.md
- libs/sevenseg/docs/reference/sevenseg/digitcounter/properties.md
- libs/sevenseg/docs/reference/sevenseg/digitcounter/set-digit-color.md
- libs/sevenseg/docs/reference/sevenseg/sevensegdigit/properties.md
- libs/sevenseg/docs/reference/sevenseg/sevensegdigit/set-digit-color.md
- libs/sevenseg/docs/reference/sevenseg/sevensegdigit/set-radix.md
- libs/sevenseg/docs/reference/sevenseg/sevensegdigit/set-scale.md
- libs/sevenseg/sevenseg.ts
Add in some reference pages for the 'sevenseg' extension.
> Add a set of reference pages for 'sevenseg'

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
Update dependencies to enable online multiplayer
> Bump dependencies: pxt-core, pxt-common-packages, and pxt-arcade-sim

- docs/skillmap/educator-info/jungle-map-info.md
- docs/skillmap/jungle.md
- docs/skillmap/jungle/jungle1.md
- docs/skillmaps.md
Replaced "Jungle Monkey Jump" with "Jungle Jump" wherever it showed up.
> Renamed map to Jungle Jump

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
> Bump sim to 0.8.14

- docs/courses/csintro2/logic/intro.md
I thought that "Is myValue (3) smaller than a testValue (5)?" sounded too generic/out of context, so I proposed something that sounded more game-specific.
> Changed initial if-statement example

- docs/courses/csintro2/logic/user-input.md
This page, like the entire course, is excellent, but I like to teach the importance of descriptive variable names, so I changed input to name and password in the respective sections on this page.
> Made variable names more descriptive

- docs/skillmap/peachtree.md
- docs/skillmap/peachtree/peach3.md
This shouldn't need review. Just adding y'all as an FYI.
Will squash when tests pass.
> Changed the name of the last level

- docs/courses/csintro1/loops/intro.md
Removed an errant apostrophe (and more importantly, demoed to my extremely attentive class (except for those who aren't)
> Fixed a grammatical mistake

- docs/hardware/dbg.md
added 'JacConnect' as alternative name for Hack-Connect XS
> added 'JacConnect' as alternative name

- docs/courses/csintro1/loops/projectiles.md
In question 2a, the blocks were not rendering in step 2. I **think** one of the backticks was out of position (hence the "maybe" in the title).
Also, changed "This tasks" to "This task" (of somewhat lesser importance, but at least I know it's correct 😀)
> Fixed mistake in blocks (maybe)

- docs/courses/csintro2/logic/intro.md
Up until this point tasks had always been labeled as Student Tasks, but here they forgot the "Student". Also, changed "Good luck!" to "Good job!", which sounded better (to my ears, anyways).
> Changed Task => Student Task

- docs/skillmap/educator-info/basic-map-info.md
The spelling of 'Greating' for 'Greeting' is not so great.
Fixes #4830
> Misspell of 'Greet' as 'Great'

- docfiles/script.html
- theme/style.less
Fixing color contrast and aria labels
> fix accessibility insights bugs

- package.json
I'll merge after the build goes through since we're skipping a bunch of versions~
> bump pxt-core -> 8.1.3

- pxtarget.json
Fix image paths.
Companion to https://github.com/microsoft/pxt/pull/9012
> Add support for multiple auth providers

- docs/arcade-devices.md
- docs/diy-hardware.md
- docs/projects.md
- targetconfig.json
Breakup the **Hardware** gallery into two galleries. One for Arcade compatible boards and one for DIY arcade game system projects.
* Arcade Compatible Devices
* DIY Hardware
Closes #4924
> split up hardware gallery into two

- docs/tutorials/valentine.md
Fixes https://github.com/microsoft/pxt-arcade/issues/4930
> Fix Typo in Valentine Tutorial

- pxtarget.json
Will keep as draft until we're ready to enable it.
> Enable Google identity provider

- docs/arcade-devices.md
- docs/diy-hardware.md
- docs/projects.md
Adjust the rank of Arcade device cards in their home screen galleries.
Closes #4923
> Change ranking of devices in galleries

- package.json
When you grab this change, be sure to:
```
npm install
npm link ../pxt ../pxt-common-packages
```
> Upgrade to TypeScript 4.8.3

- docs/ide-tour.md
Remove 'a' from 'try your a game' in the IDE tour page....oh, I found some more edits to do in this thing.
> IDE tour not on its 'a' game

- kiosk/src/Models/Kiosk.ts
added two functions to add custom games to the scrolling game list
> Added functions to add custom games to game list

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
> use sim v0.9.4

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
New simulator picks up custom pointerevents support.
> updated sim to v0.9.5

- docs/hour-of-code-2022.html
- docs/static/hour-of-code/2022/styles.css
Made changes that we discussed in the group.  FYI will squash when test pass to confirm images are pulling correctly.
> Hoc2022 realease updates

- docs/hour-of-code-2022.html
- docs/static/hour-of-code/2022/styles.css
Issues with getting correct path from static.  Will need to squash to test.
> Broken links from static page

- docs/hour-of-code-2022.html
- docs/static/hour-of-code/2022/styles.css
Dealing with issue on static CSS and not finding fonts and images inside of static folder
> Fix path issue on static css

- pxtarget.json
Re: https://github.com/microsoft/pxt-arcade/issues/2130
> Enable sound effect editor in monaco

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
Adds mouse wheel events to pointer-events mode.
> bump to arcade-sim 0.9.6

- docs/beta-ref.json
Point for a week or so to focus all testing on stable channels
> Point beta to v1.10 for now

- docs/skillmap/balloon.md
- docs/skillmap/mole.md
> removed /test

- docs/hour-of-code/all.md
- docs/skillmap/balloon/balloon1.md
- docs/skillmap/balloon/balloon2.md
- docs/skillmap/balloon/balloon3.md
- docs/skillmap/balloon/balloon4.md
- docs/skillmap/mole/mole1.md
Made the set variable open the Sprites category
Updated the HoC (all) page
Took away the prompt to use full screen for trying the game (until we have a better call to action).
> More small HoC fixes

- docs/hour-of-code/all.md
- docs/skillmap/balloon/balloon1.md
- docs/skillmap/balloon/balloon4.md
- docs/skillmap/mole.md
- docs/skillmap/mole/mole1.md
Trying to add a newline to the whack-the-mole map
laying out the HoC (All) page a little more nicely (and removing ! since all cards weirdly add periods to the end?)
> Some more tiny changes

- docs/tutorials/alien.md
- docs/tutorials/barrel-dodger.md
- docs/tutorials/catch-the-football.md
- docs/tutorials/chase-the-basketball.md
- docs/tutorials/chase-the-pizza-update.md
- docs/tutorials/chase-the-pizza.md
- docs/tutorials/collect-the-clovers.md
- docs/tutorials/free-throw.md
- docs/tutorials/froggy.md
- docs/tutorials/galga.md
- docs/tutorials/happy-flower.md
- docs/tutorials/hundred.md
- docs/tutorials/lander.md
- docs/tutorials/lemon-leak.md
- docs/tutorials/maze.md
- docs/tutorials/nicoles-favorites-frenzy.md
- docs/tutorials/paddle.md
- docs/tutorials/spy/chase-the-pizza.md
- docs/tutorials/spy/galga.md
- docs/tutorials/spy/happy-flower.md
- docs/tutorials/spy/lemon-leak.md
- docs/tutorials/spy/paddle.md
- docs/tutorials/winter.md
Add the modifiers for the inline block highlight text to modify the click-to-open toolbox behavior - tutorials edition.
Closes: #4994
> Inline block text doc mods for toolbox opening - tutorials

- docs/skillmap/balloon/balloon1.md
- docs/skillmap/balloon/balloon2.md
- docs/skillmap/balloon/balloon4.md
- docs/skillmap/mole/mole2.md
- docs/skillmap/mole/mole3.md
- docs/test/skillmap/target/target1.md
FYI
Changes to balloon and mole are safe
No one is using Target yet.
> Some fixes pointed out by Sarah and game over work

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- docs/beta-ref.json
- package.json
- upgrade to sim v0.10.1 (pointer-events fix)
- unlock /beta
> Simv0.10.1

- pxtarget.json
This should help all variants of Spanish.
> Enabling es-ES as the base language 

- docs/skillmap/clicker-themed/clickert1.md
- docs/skillmap/forest_new/forest1.md
- docs/skillmap/interface/activity1.md
- docs/skillmap/jungle/jungle1.md
- docs/skillmap/platformer/activity1.md
- docs/skillmap/rockstar/rockstar1.md
- docs/skillmap/shark/shark1-simple.md
- docs/skillmap/space/activity1.md
- docs/skillmap/space/space1.md
- docs/skillmap/star/star1.md
- docs/skillmap/star/star2.md
- docs/skillmap/story/story1.md
- docs/skillmap/turkey/turkey1.md
- docs/skillmap/zoo/zoo1.md
- docs/skillmap/zoo/zoo2.md
- docs/skillmap/zoo/zoo2a.md
Modify the remaining mentions of "Game Window Tab" in skillmaps to correctly refer to the new UI.
Closes #5118
> Change mentions of 'Game Window Tab' for new UI

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
pick up multiplayer fixes
* https://github.com/microsoft/pxt-common-packages/pull/1378
* https://github.com/microsoft/pxt-common-packages/pull/1379
* https://github.com/microsoft/pxt-arcade-sim/pull/79
> Bump mult controls

- docs/game-jam.md
Republish the 'Flying Through Time' GameJam project with updated extension dependencies.
Primarily - https://github.com/pelikhan/pxt-rtttl/releases/tag/v0.0.12
Closes #3848
> Republish 'Flying Through Time'

- docs/arts-and-crafts.md
Remove the 'Kitty Wumpus' project since it's a linkout and won't work when editor is offline.
Closes #4033
> Remove 'Kitty Wumpus' project

- docs/arcade-devices.md
- docs/hardware.md
Update URL for Retro Arcade product.
> Updating the elecfreaks product page as per their request

- docs/courses/csintro2/logic/while.md
Add a clarifying note for "Student task 2" and include some additional formatting.
Closes #5178
> Update the "Logic in Loops" lesson for csintro2

- docs/test/skillmap/mole.md
> Fixed typo

- pxtarget.json
re: https://github.com/microsoft/pxt/pull/9146, will need to bump pxt for this to do anything but fine to merge in
> enable multiplayer share button flag

- docs/test/skillmap/balloon/balloon1.md
- docs/test/skillmap/balloon/balloon2.md
- docs/test/skillmap/balloon/balloon3.md
- docs/test/skillmap/balloon/balloon4.md
- docs/test/skillmap/mole.md
- docs/test/skillmap/mole/mole1.md
- docs/test/skillmap/mole/mole2.md
- docs/test/skillmap/mole/mole3.md
FYI
These are all in test so I'll merge when tests pass.
> Updating HoC to use extensions

- targetconfig.json
This is Carnival extension requested by Kiki
> Adding carnival to the approved repo

- docs/test/skillmap/mole/mole2.md
- docs/test/skillmap/mole/mole3.md
FYI
Found two more issues leftover from converting extension
> Found 2 more issues

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
pick up sound so ideally we can test on staging, will let build go through to make sure all versions good~
> bump pxt/common-packages/sim

- docs/test/skillmap/balloon/balloon1.md
- docs/test/skillmap/balloon/balloon2.md
- docs/test/skillmap/balloon/balloon3.md
The first 3 levels were using a different version of carnival.  Not sure how that would keep level 1 from loading, but I'm trying it.
> Check if changing carnival package fixes issues

- docs/test/skillmap/balloon.md
it was the gal-darn leading slashes!
> Fix balloon map

- docs/test/skillmap/balloon/balloon1.md
- docs/test/skillmap/balloon/balloon2.md
- docs/test/skillmap/balloon/balloon3.md
- docs/test/skillmap/balloon/balloon4.md
FYI
Finished playthrough and realized that the timer should be a game over lose.
> Updated countdown to lose game

- docs/test/skillmap/mole/mole1.md
- docs/test/skillmap/mole/mole2.md
- docs/test/skillmap/mole/mole3.md
- docs/test/skillmap/mole/mole4.md
FYI
I'll squash when tests pass
> Fixed issues Jaq found

- docs/test/skillmap/turkey/turkey1.md
- docs/test/skillmap/turkey/turkey2.md
- docs/test/skillmap/turkey/turkey3.md
FYI only
Changed the carnival winTypes to WinTypes
> Fixes from Turkey Day runthrough

- docs/test/skillmap/mole.md
- docs/test/skillmap/mole/mole1.md
- docs/test/skillmap/mole/mole2.md
- docs/test/skillmap/mole/mole3.md
- docs/test/skillmap/mole/mole4.md
Just an FYI
Changed the extension to be the correct one
> Update Mole to use new carnival ext

- package.json
- pxtarget.json
the disappearance of the music editor did not go unnoticed:
https://forum.makecode.com/t/music-sequencer-for-makecode-arcade/16248/2
> bump core, common, and enable song editor

- docfiles/script.html
this is why typescript is a good thing
> Fix host game button always appearing

- docs/beta-ref.json
Probably fine to merge now that the test day is done? Would be good to get music editor back in /beta as several people have asked for it / noticed it's gone~
> unpin beta

- docs/test/skillmap/balloon.md
- docs/test/skillmap/balloon/balloon3.md
- docs/test/skillmap/balloon/balloon4.md
- docs/test/skillmap/mole.md
- docs/test/skillmap/turkey.md
- docs/test/tutorials/wakanda-forever.md
- docs/tutorials/wakanda-forever.md
Shipping wakanda pixel and test changes.
> Updating files based on team suggestions

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
pick up https://github.com/microsoft/pxt-arcade-sim/pull/83 and https://github.com/microsoft/pxt-arcade-sim/pull/82
> [stable1.11] pick up pxt-arcade-sim fixes

- docs/skillmap/turkey.md
FYI, this is just an image change
> Updated turkey to use new bg image

- docs/test/tutorials/wakanda-forever.md
Just an FYI
Polished Wakanda a little more…added two places to have them stop and look at their game.
> Last-minute polishes for Wakanda

- docs/test/tutorials/target.md
- docs/tutorials/target.md
Just an FYI…this one isn't touched yet
> Re-fixed the final sentence.

- docs/test/tutorials/arrow.md
> Adding the arrow game

- docs/test/tutorials/arrow.md
- docs/test/tutorials/horse.md
> Polishes after runthrough

- docs/skillmap/balloon/balloon1.md
- docs/skillmap/mole/mole1.md
left of the file type from the .png
I'll squash when tests pass
> typo fixes

- pxtarget.json
Safe to merge now but won't do anything until https://github.com/microsoft/pxt/pull/9321 is released
> enable music field editor in monaco

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
Bumping all three to pick up presence bar changes into beta~
> Presence in editor bumps

- docs/hero-banner.md
**Don't merge until after the Arcade release**
closes https://github.com/microsoft/pxt-arcade/issues/5491
Part 1 (separate PR: https://github.com/microsoft/pxt-arcade/pull/5561):
- Added multiplayer banner as the first in the hero banner gallery
**Part 2 (this PR):**
- Removed the Holiday Bow Battle banner
- Corrected labels and titles to use consistent capitalization (title case)
> Add multiplayer banner to hero banner gallery - Part 2

- docs/test/skillmap/balloon/balloon1.md
- docs/test/skillmap/balloon/balloon2.md
- docs/test/skillmap/balloon/balloon3.md
- docs/test/skillmap/balloon/balloon4.md
- docs/test/skillmap/dino/dino2.md
- docs/test/skillmap/mole/mole1.md
- docs/test/skillmap/mole/mole2.md
- docs/test/skillmap/mole/mole4.md
- docs/test/tutorials/collect-clovers.md
FYI
Updating test files based on playthrough
> Updates after trying

- docs/test/skillmap/balloon/balloon3.md
- docs/test/skillmap/balloon/balloon4.md
- docs/test/tutorials/horse.md
FYI only
These should only affect /test
> More test fixes

- docs/skillmap/balloon/balloon1.md
- docs/skillmap/balloon/balloon2.md
- docs/skillmap/balloon/balloon3.md
- docs/skillmap/balloon/balloon4.md
- docs/skillmap/mole/mole1.md
- docs/skillmap/mole/mole2.md
- docs/skillmap/mole/mole3.md
- docs/skillmap/mole/mole4.md
- docs/test/skillmap/balloon/balloon4.md
Pushing the fixed versions that were in the /test folder to live.
I fixed, tested, debugged, and tested again until I could run through with no errors.  If you want to check for yourself, these are exact duplicates of the versions in test, so you can play through:
http://arcade.makecode.com/--skillmap#docs:/test/skillmap/mole
and
http://arcade.makecode.com/--skillmap#docs:/test/skillmap/balloon 
In the meantime, the original versions are broken due to extension changes.
> Fixing for beta going live

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
I'll let build go through before merging & bumping stable~
> [stable1.12] bump pxt/pxt-common-packages/pxt-arcade-sim

- docs/multiplayer.md
Fix bullet list rendering in `multiplayer.md` by removing newlines between list items.
Closes #5622
> Fix bullet list item render in 'multiplayer.md'

- docs/skillmap/balloon/balloon1.md
- docs/skillmap/turkey/turkey1.md
- docs/test/skillmap/adventure/adventure1.md
- docs/test/skillmap/balloon/balloon1.md
- docs/tutorials/hawk.md
FYI
A couple of updates to issues found by Shiela. Also giving the Hawks tutorial a place for url purposes.
> Pushing some changes with fixes

- docs/test/skillmap/adventure/adventure1.md
FYI only
Updated the first adventure level in the /test folder.
> Updated level 1 for no dice

- docs/graveyard/skillmap/star-sing2/star1.md
- docs/graveyard/skillmap/star-sing2/star2.md
- docs/graveyard/skillmap/star-sing2/star3.md
- docs/graveyard/skillmap/star-sing2/star4.md
- docs/test/skillmap/adventure/adventure1.md
- docs/test/skillmap/adventure/adventure2.md
- docs/test/skillmap/adventure/adventure3.md
FYI Only
Adding updates from team runthrough of D&D.
Also made the archived Sing2 images point to the right spot so we can continue using that map as a partner showcase for other brands to review.
> More Adventure + Sing2 Updates

- docs/test/skillmap/adventure.md
- docs/test/skillmap/adventure/adventure3.md
> Updated Adventure

- docs/tutorials/chase-the-pizza.md
Add some style options to make the block text clicks go to the proper categories.
Closes #5706
> Style 'chase the pizza' text for proper categories

- libs/corgio/corgio.ts
- libs/corgio/docs/reference/corgio.md
- libs/corgio/docs/reference/corgio/add-to-script.md
- libs/corgio/docs/reference/corgio/bark.md
- libs/corgio/docs/reference/corgio/camera-follow.md
- libs/corgio/docs/reference/corgio/create.md
- libs/corgio/docs/reference/corgio/horizontal-movement.md
- libs/corgio/docs/reference/corgio/update-sprite.md
- libs/corgio/docs/reference/corgio/vertical-movement.md
Add a very base set of reference pages for the "Corgio" extension. Include a main page as a destination for the "Learn More" link.
Closes #5576
> Corgio extension reference and main pages

- docs/skillmap/story/story-example.md
- docs/test/skillmap/story/story1.md
- docs/test/skillmap/story/story2.md
- docs/test/skillmap/story/story3.md
- docs/test/skillmap/story/story4.md
FYI - Nothing to see here
Edited the story map one more time after run through.
> Edited story after runthrough

- package.json
Includes:
https://github.com/microsoft/pxt/commit/f81ebec367141184d22e181b76ccd55a40005618
https://github.com/microsoft/pxt/commit/902611562d7d1d8489bfae8591dc4c40fa642112
@thsparks FYI
> [Stable1.12] bump core to 8.5.34

- package.json
pick up https://github.com/microsoft/pxt/pull/9401
> bump pxt-core ref to pick up vscode-extension fixes

- docs/hero-banner.md
- docs/tutorials.md
Please review!
Super simple change to remove Wakanda, but I don't want to merge homepage changes without other eyes.
> Removing Wakanda from Homepage

- package.json
pick up https://github.com/microsoft/pxt/pull/9412, https://github.com/microsoft/pxt/pull/9413
> [stable1.12] pick up pxt changes

- docs/skillmap/adventure/adventure1.md
- docs/skillmap/adventure/adventure2.md
- docs/skillmap/adventure/adventure3.md
- docs/skillmap/balloon/balloon1.md
- docs/skillmap/balloon/balloon2.md
- docs/skillmap/balloon/balloon3.md
- docs/skillmap/balloon/balloon4.md
- docs/skillmap/mole/mole1.md
- docs/skillmap/mole/mole2.md
- docs/skillmap/mole/mole3.md
- docs/skillmap/mole/mole4.md
- docs/test/skillmap/adventure/adventure1.md
- docs/test/skillmap/adventure/adventure2.md
- docs/test/skillmap/adventure/adventure3.md
- docs/test/skillmap/story-new/story1.md
- docs/test/skillmap/story-new/story2.md
- docs/test/tutorials/arrow.md
- docs/test/tutorials/hawk.md
- docs/test/tutorials/horse.md
- docs/test/tutorials/target.md
- docs/test/tutorials/time-flies.md
Adding @jwunderl to review, but I tested each one in the tutorial-tool, so I will probably merge tomorrow even without extra approval.
> These should be nearly all version updates for extensions

- docs/hero-banner.md
- docs/skillmaps.md
- targetconfig.json
I'm going to go ahead and publish this so it's there after caches clear tomorrow.  I'll test to make sure it didn't break anything.  If it does, I'll undo changes (but it shouldn't).
> Publishing Adventure (DnD)

- docs/test/skillmap/star/star4.md
> Adding music to Star

- docs/test/skillmap/dino/dino3.md
- docs/test/skillmap/star/star1.md
- docs/test/skillmap/star/star2.md
> Fixed a couple small issues found in the session

- docs/skillmaps.md
I'm going to try to use these whenever assets need to disappear
> Adding "limited time" ribbon to Adventure skillmap

- docs/projects.md
- theme/site/globals/site.variables
Arcade theming for the cloud projects card.
> arcade: theming for cloud projects card

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
from https://github.com/microsoft/pxt-arcade-sim, richard already bumped the pxt-core side~
> [stable1.12] pick up theme sim changes

- docs/courses/carnival/lesson.md
- docs/skillmap/racer.md
- docs/tutorials/dunk.md
A couple of small changes and a fix for racer.
> Post publication updates

- package.json
- webmanifest.json
requires https://github.com/microsoft/pxt/pull/9504
> don't force portrait mode in installed pwa

- docs/skillmap/jungle/jungle7.md
- docs/skillmap/space/activity4.md
> Two tiny fixes

- docs/SUMMARY.md
Add some local target developer topics to the main SUMMARY.
Closes #5934
> Add dev topics to SUMMARY

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpr.yml
- .github/workflows/pxt-buildpush.yml
see https://github.com/microsoft/pxt-common-packages/pull/1451
> Update checkout, setup-node to avoid deprecated node versions

- docs/courses/carnival.md
FYI
Teacher homepage for Carnival
> Uploading teacher page for the Carnival Course

- docs/courses/carnival/lesson.md
FYI
Uploading the student page for the Carnival curriculum
> Uploading student page for Carnival

- docfiles/script.html
fix https://github.com/microsoft/pxt-arcade/issues/5139 since it was labelled for hotfix~
> bump script page year to 2023

- docfiles/script.html
> [stable1.12] bump script page year to 2023

- docs/skillmap/sparks/sparks2.md
FYI
Changing the last line until we have level 3 ready.
> Changed end level text.

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
v0.11.5
For the changes that will be in effect, look at this PR: https://github.com/microsoft/pxt-arcade-sim/commit/36538c364617fc93e5c95d0e98975fd7f4e433e6
> Bumping pxt-arcade-sim for MakeCodeJr theming

- docs/test/mkj/goal1/goal1-1.md
- docs/test/mkj/goal1/goal1-2.md
This is working about as well as possible within the limitations we've got ;)
https://arcade.makecode.com/beta#recipe:/test/mkj/goal1/goal1-1
> Updated to be less messy

- editor/extension.ts
- package.json
On more tick event fix, invalidate translations that will break when switching languages, upgrade rule for handling those
> [stable1.12] hotfix ports

- docs/gamejam/prehistoric.html
- docs/hero-banner.md
- docs/static/gamejam/jams/prehistoric/info.json
- docs/static/gamejam/lib/gamejam.css
- docs/static/gamejam/lib/gamejam.js
- docs/static/gamejam/lib/gamejam.ts
Also removes the submit button and the hero banner for the jam.
> Adding all of the Prehistoric Jam entries

- docs/kiosk-data/GameList.json
- docs/kiosk-data/manifest.json
- ~~Deleted kiosk codebase from this repo.~~
- ~~Added kiosk-ref.json~~
- Copied kiosk's config files over to `docs/kiosk-data`. This is where "new" kiosk will try to fetch them from at startup.
> [Arcade] Move kiosk codebase to pxt repo

- docs/static/gamejam/jams/prehistoric/rules.md
Fixes https://github.com/microsoft/pxt-arcade/issues/6020
> Fix link on gamejam page

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- editor/tsconfig.json
- libs/shader/pxt.json
- libs/shader/shims.d.ts
- package.json
- pxtarget.json
build expected to fail atm as it needs a few other misc fixes in pxt-common-packages.
fixes I'll need for build to work:
* https://github.com/microsoft/pxt-common-packages/pull/1456
* https://github.com/microsoft/pxt/pull/9623
* https://github.com/microsoft/pxt-arcade-sim/pull/100
will port https://github.com/microsoft/pxt-arcade/commit/845b99290415605ef8dee09299391b95806949a3 to master separately, branches all mixed up atm to get these ports out~
Here's a test build for now https://arcade.makecode.com/app/5d3c49731a73cdd0d1b978664e2b089a0fb64303-549b80d855
> [stable1.12] game lib fixes

- pxtarget.json
> Cherry pick clever support

- docs/hero-banner.md
- docs/multiplayer-tutorials.md
- docs/test/tutorials/pizza-party.md
- docs/tutorials/pizza-party.md
Need to remove the TMNT IP over the weekend.  I've made the tile/banner changes in this PR, as well as fixes from testing the new version of the pizza party tutorial. 
Since this touches Arcade homepage, I'll wait for approval. 
Adding @srietkerk @kimprice and @thsparks this time so that they get visibility into the process for next time.
> Removing TMNT IP

- docs/skillmap/educator-info/spark-map-info.md
- docs/skillmap/sparks/sparks1.md
- docs/skillmap/sparks/sparks2.md
- docs/test/skillmap/globetrotters.md
> Fix globetrotters and update Sparks

- docs/test/skillmap/class.md
- docs/test/skillmap/class/class1.md
- docs/test/skillmap/class/class2.md
- docs/test/skillmap/class/class3.md
- docs/tutorials/pizza-party.md
FYI
Updates to the Tutorial Tutorial (Kiki's Class) as well as fixes for:
https://github.com/microsoft/pxt-arcade/issues/6109
https://github.com/microsoft/pxt-arcade/issues/6110
> KikisClass plus PizzaParty updates

- targetconfig.json
> Fixing variants for microbit shields

- docs/hardware.md
- targetconfig.json
Update the product link for the "game:bit" board to use 'en' locale.
Closes #6120
> Update product link for 'game:bit'

- docs/test/tutorials/globetrotters.md
Updated Globetrotters tutorial to slim it down.
> Updated Globetrotters

- docs/test/tutorials/globetrotters.md
FYI, went through and changed Hotshot to two words in all files and extensions.
> Changed Hotshot to Hot Shot

- targetconfig.json
Added:
- MakeCode Racers
- BUG PRESIDENT: THE GAME
- Joey's Pool Sharks
- Best Nest
- NINJA
- Auto and Ollie
Removed:
- Secure the River
- Strawberry Slam
- Save the Forest
- Cave Explorer
> Update kiosk games list

- targetconfig.json
Used the title screen, the art is great.
Resolves https://github.com/microsoft/pxt-arcade/issues/6177
> kiosk: give dino zoo a thumbnail

- docs/hardware/kiosk.md
Resolves https://github.com/microsoft/pxt-arcade/issues/6188
Resolves https://github.com/microsoft/pxt-arcade/issues/6186
Resolves https://github.com/microsoft/pxt-arcade/issues/6185
Resolves #6183
I also made a few stylistic updates. Let me know if you don't like them and I can revert:
* Renamed "Shoe Box" --> "Shoebox", to be consistent with with https://arcade.makecode.com/hardware/shoebox-controller
* Minor wording on joystick use
* Use of `<kbd>` tag to stylize keyboard keys.
> docs: update kiosk.md

- docs/test/tutorials/turkey-jr.md
FYI 
Adding divider lines to separate the anigifs a little more from the instructions.
> Added divider lines

- docs/tutorials/turkey-jr.md
FYI
Moving Turkey-Jr from the test folder into the live tutorial folder.
> Moving turkey into live folder

- docs/gamejam/dec2023.md
FYI
Updating the placeholder page since apparently some had it bookmarked
> Updating original Dec2023 page

- docs/hero-banner.md
Please review. 
Added a new banner for the snow globe tutorial and rerouted the turkey day tutorial to Turkey-Jr.
> Update hero banner for snowglobe +

- docs/gamejam/community.md
- docs/test/mcj/gopher/gopher1.md
- docs/test/tutorials/free-throw.md
> Updating GameJam page ++

- docs/tutorials/froggy.md
Fixing the block config for the "Time Flies" tutorial, which has some TS errors:
* `if` statements can't have an empty condition
* the `list` variable wasn't declared anywhere
> Fix block config for froggy

- pxtarget.json
Fixes https://github.com/microsoft/pxt-arcade/issues/6337
> Adding russian to arcade

- editor/extension.ts
- package.json
Just fixing the type references for pxteditor with the new module change
> Consume pxteditor changes and upgrade core

- docs/gamejam/female-gamechangers.html
- docs/static/gamejam/jams/female-gamechangers/rules.md
- docs/static/gamejam/jams/female-gamechangers/style.css
Makes everything look nice on mobile
Also updates the submission link and past game jam link
> Fix gamejam mobile css and links

- targetconfig.json
Adding rhombus rush to the kiosk with all of the levels designed by forum members!
> Add rhombus rush to kiosk

- package.json
Bringing in the sequencer fixes for the simulator
> [Stable1.12]Bump pxt-core and pxt-common-packages

- libs/hw---n3/config.ts
> Microbit pin mapping

- docs/gamejam/female-gamechangers.html
- docs/static/gamejam/jams/female-gamechangers/info.json
- docs/static/gamejam/jams/female-gamechangers/rules.md
Also removing the submission links/timer from the gamejam page
> Add entries for female gamechangers jam

- package.json
Bumping for the Immersive Reader token fix
> Bump pxt-core -> 8.5.62

- docs/test/skillmap/forest/forest2.md
- docs/test/skillmap/forest/forest3.md
- docs/test/skillmap/forest/forest4.md
- docs/test/skillmap/forest/forest5.md
- docs/test/skillmap/forest/forest6.md
- docs/test/tutorials/bubbles.md
This doesn't contain any spy work at all.  Just updates for Forest and Bubble.
> Fixes for Forest and Bubble

- docs/game-jam.md
- docs/hero-banner.md
Someone on the forum reminded me that I forgot to do this....
> Add game jam winners to home and remove banner

- docs/game-jam.md
- docs/hero-banner.md
Cherry picking the game jam winners to the v1 branch
> [V1] add game jam winners to home and remove banner (#6411)

- targetconfig.json
> Change the name of Kitronik arcade shield board

- libs/hw---n3/config.ts
https://github.com/microsoft/pxt-arcade/pull/6374
> [Stable1.12] Cherry picking Microbit pin fix to stable

- targetconfig.json
> Enabling tutorial for code-ninja

- pxtarget.json
re: https://github.com/microsoft/pxt-microbit/pull/5807
> Enable uploadDocs

- package.json
Getting my fix for the crowdin upload
> Bump pxt-core to 10.2.7

- docs/hero-banner.md
- docs/tutorials.md
Adding limited time Scott Kelly mission to home page with banner.
---
> Adding CodeNinjas activity to Home Page

- docs/hero-banner.md
- docs/tutorials.md
Cherry-picking the Code Ninjas home page update to V1.
> Adding CN activity to Home Page (#6506)

- docfiles/script.html
@kiki-lee FYI
this does not add support for the changing icons based on the sprite for each player, just switching players. if it's not too complicated then i'll open another PR to add support for that
> add the multiplayer presence bar to the script page

- package.json
Updating both to the latest since they were fairly behind
> Bump pxt-core and pxt-common-packages to latest

- docs/tutorials/bubbles.md
- docs/tutorials/lyla-jr.md
Added tracking pixel to the `bubbles.md` and `lyla-jr.md` files to track user engagement for Code.org.
> Adding Tracking Pixel

- docs/tutorials/bubbles.md
- docs/tutorials/lyla-jr.md
Adding tracking for Code.org. Cherry-picking to V1.
> Adding Tracking Pixel (#6577)

- docs/tutorials/bubbles.md
> Added missing png from Code.org

- docs/tutorials/bubbles.md
The tracker didn't work without the .png
> Adding PNG extension to Bubble tutorial

- package.json
Bringing in CDN changes to pxt-core.
> Bump pxt minor version to bring in CDN changes

- package.json
Pulling in CDN changes from pxt-core.
> Pull in CDN changes

- docs/static/gamejam/jams/cozy/info.json
updating pecan4's game per their request:
https://forum.makecode.com/t/announcement-makecode-arcade-cozy-game-jam/31793/273?u=richard
i don't want to make a habit of doing this, but their game had a pretty bad bug so i'll let it slide :)
> Update cozy game entry

- docs/static/gamejam/jams/cozy/info.json
fixes https://github.com/microsoft/pxt-arcade/issues/6615
adding in some late entries from @michaelcaplan's class
> adding some late game jam entries

- docs/game-jam.md
- docs/projects.md
- docs/static/gamejam/jams/cozy/info.json
- docs/static/gamejam/jams/cozy/rules.md
> add cozy game jam winners

- docs/game-jam.md
- docs/projects.md
* add cozy game jam winners
* fix thumbnail
* Update docs/game-jam.md
---------
> [V1] Cherry pick cozy game jam carousel updates

- package.json
grabbing all of my recent fixes
> bump pxt-core to 11.3.12

- pxtarget.json
Also sorted the list of locales alphabetically for better readability
> Enabling Irish language

- package.json
just grabbing https://github.com/microsoft/pxt-common-packages/pull/1493
will hotfix tomorrow
> [Stable1.12] bump pxt-common-packages to 10.3.27

- package.json
build will fail on this because pxt is still bumping
> bump pxt-core to 11.3.22 and pxt-common-packages to 12.2.4

- package.json
fixing the rpi C++ build error
> bump pxt-common-packages to 12.2.5

- docs/courses/csintro/blocks/unit-2/lab0201-part1.md
- docs/courses/csintro/blocks/unit-2/lab0201-part2.md
- docs/courses/csintro/blocks/unit-2/lab0201-part3.md
- docs/courses/csintro/blocks/unit-2/lab0201-part4.md
- docs/courses/csintro/blocks/unit-2/lab0201-part5.md
- docs/courses/csintro/blocks/unit-2/lab0206-part1.md
- docs/courses/csintro/blocks/unit-2/lab0206-part2.md
- docs/courses/csintro/blocks/unit-2/lab0206-part3.md
- docs/courses/csintro/blocks/unit-2/lab0206-part4.md
- docs/courses/csintro/blocks/unit-2/skillmap.md
Cherry-picking recent updates to V1
> Cherry-picking the second half of Lab 2 

- .github/workflows/pxt-buildmain.yml
- .github/workflows/pxt-buildpush.yml
- package.json
forgot to bump with the new keyboard changes!
> bump pxt-arcade-sim to v0.11.13

- theme/color-themes/arcade-dark.json
- theme/color-themes/arcade-legacy.json
- theme/color-themes/arcade-light.json
- theme/color-themes/overrides/arcade-dark-overrides.css
Fixes some of the dark theme issues spotted in testing today. Generally speaking, each commit = 1 issue (though some are split in pxt changes too: https://github.com/microsoft/pxt/pull/10416).
Fixes https://github.com/microsoft/pxt-arcade/issues/6775
Fixes https://github.com/microsoft/pxt-arcade/issues/6772
Fixes https://github.com/microsoft/pxt-arcade/issues/6765
Fixes https://github.com/microsoft/pxt-arcade/issues/6769
Fixes https://github.com/microsoft/pxt-arcade/issues/6759
Upload Target: https://arcade.makecode.com/app/5711563fab6ebb9e9bae48fac06f5fed01f9053d-867f791e15
> Arcade Dark Theme Fixes

- docs/community.md
Fixes https://github.com/microsoft/pxt-arcade/issues/6249
> Removing Adventures of Sam and Nate

- docs/tutorials/snow.md
fixes https://github.com/microsoft/pxt-arcade/issues/6607
> fix song reference in snowglobe tutorial

- docs/vscode.md
> update vscode.dev/makecode route

- docs/test/skillmap/intermediate-skillmap.md
quick test to see if the changes to the newer cert naming system were successful. this will not impact the live game maker guide skillmap.
> testing game maker guide changes

- docs/reference/controller.md
Fix a bad 'See also' link in the 'Controller' reference main page.
Closes #6853
>  Bad link in the 'Controller' reference main page.

- targetconfig.json
> Releasing 2.0.40 to electron app

- package.json
bumping to version 12.3.3 (sprite rotation changes)
> Bump pxt-common-packages to 12.3.3

- docs/gamejam/all.md
Add in a "Cozy Jam" card the previous jams list.
Closes #6915
> Add 'Cozy' jam card to the 'gamejam/all' page

- docs/community.md
ADM_F made a topic for it:
https://forum.makecode.com/t/crate-dungeons/36126
> Replace crate dungeons forum url

- docs/courses/arcadecon/2025.md
- docs/educators.md
- docs/test/tutorials/decrypt.md
> Updates before Bellevue Teachers Workshop

- package.json
let's finally get that patch fix out today...
> Update pxt-core to 11.3.59

- package.json
bumping to get the code carryover fixes for bug arena
> [stable2.0] bump pxt-core to 11.3.62

- docs/skillmap/bug-arena/introduction.md
Added an introduction to the Bug Arena tutorial, explaining the mechanics and objectives without coding.
> Added no coding in intro

- docs/skillmap/bug-arena.md
Updated the descriptions field for tutorials in Bug Arena Skillmap
> Added tutorial descriptions
